### ISSUE TITLE
ModuleNotFoundError when importing S3_hook

### ISSUE THREAD

**Issue by hughcameron** [bitnami/bitnami-docker-airflow#1]
**Description**

When running a DAG that writes files to an S3 bucket via the S3_hook an module not found error occurs.

**Steps to reproduce the issue:**

1. Create S3 connection via Admin > Connections in the Airflow interface
2. Develop a DAG with `from airflow.hooks.S3_hook import S3_hook`
3. Execute DAG

**Describe the results you received:**
Stack trace of error below:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-2ad1e3d42f30> in <module>
----> 1 from airflow.hooks.S3_hook import S3_hook

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/hooks/S3_hook.py in <module>
     20 
     21 from airflow.exceptions import AirflowException
---> 22 from airflow.contrib.hooks.aws_hook import AwsHook
     23 
     24 from six import BytesIO

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py in <module>
     18 # under the License.
     19 
---> 20 import boto3
     21 import configparser
     22 import logging

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/boto3/__init__.py in <module>
     14 import logging
     15 
---> 16 from boto3.session import Session
     17 
     18 

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/boto3/session.py in <module>
     15 import os
     16 
---> 17 import botocore.session
     18 from botocore.client import Config
     19 from botocore.exceptions import DataNotFoundError, UnknownServiceError

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/botocore/session.py in <module>
     26 import botocore.configloader
     27 import botocore.credentials
---> 28 import botocore.client
     29 from botocore.exceptions import ConfigNotFound, ProfileNotFound
     30 from botocore.exceptions import UnknownServiceError, PartialCredentialsError

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/botocore/client.py in <module>
     14 import functools
     15 
---> 16 from botocore import waiter, xform_name
     17 from botocore.auth import AUTH_TYPE_MAPS
     18 from botocore.awsrequest import prepare_request_dict

~opt/bitnami/airflow/venv/lib/python3.6/site-packages/botocore/waiter.py in <module>
     16 
     17 from botocore.utils import get_service_module_name
---> 18 from botocore.docs.docstring import WaiterDocstring
     19 from .exceptions import WaiterError, ClientError, WaiterConfigError
     20 from . import xform_name

ModuleNotFoundError: No module named 'botocore.docs'
```

**Describe the results you expected:**

No error upon import.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 47
Server Version: 17.05.0-ce
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: fd189da3e13a3ef3d6d9eb73c5cd4697b4536cdd (expected: 9048e5e50717ea4497b757314bad98ea3763c145)
runc version: a2d6e07aab95ff37fb63cf5dec3c40d29940194f (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 7a83305 (expected: 949e6fa)
Security Options:
 apparmor
Kernel Version: 3.10.105
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.719GiB
Name: Briggin
ID: ILID:MGTF:7WZO:CV5G:KTE4:QNT5:H355:XDEG:NXUQ:KT6R:ZUGN:7DSC
Docker Root Dir: /volume1/@docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by tompizmor** [comment]
Hi @hughcameron,

Thanks for letting us know. Airflow can be installed with different [extra packages](https://airflow.apache.org/installation.html#extra-packages) and the S3 one is not included in the bitnami docker image.

We will work on adding it and release a new version. I will update this issue once the release is completed.

**Comment by tompizmor** [comment]
Hi @hughcameron,

I just wanted to let you know that we have now included the `S3` module in airflow so you should not get that error if you try with the latest version.
Please let me know if you find any other issue.

**Comment by hughcameron** [comment]
Thanks so much @tompizmor - I'll check it out.

**Comment by tompizmor** [comment]
OK! Let me know whatever is the result!

**Comment by hughcameron** [comment]
Hey @tompizmor - just following up. I still wasn't able to to get the hook import working from the image but thanks to your comment above it worked after I configured airflow with a `requirements.txt` like this:

```
botocore>=1.12
boto3>=1.9
apache-airflow[s3]>=1.10
```

**Comment by AnthonyMRodrigues** [comment]
Hi.
I started to use this project and even using the last docker image version, still getting the same error that was reported before.
Any help?

**Comment by tompizmor** [comment]
@AnthonyMRodrigues, could you give us some instructions so we can try to reproduce the issue?
Do you have any sample DAG that we can use that uses the s3 module?

**Comment by AnthonyMRodrigues** [comment]
@tompizmor thanks for helping me.
My DAG is simple, just call a class that starts S3.

Dag:
`from src.imports import dataToS3
S3Obj = dataToS3
S3Obj.list()
`

Class:

`from airflow.hooks.S3_hook import S3Hook
from airflow.hooks.base_hook import BaseHook
def __init__():
self.s3 = self.s3 = S3Hook(aws_conn_id='s3-datalake')`

After this class init, I got the same error.

> [2019-06-18 20:48:03,097] {logging_mixin.py:95} INFO - Importation Error:  No module named 'botocore.docs'
[2019-06-18 20:48:03,098] {python_operator.py:113} INFO - Done. Returned value was: None

**Comment by AnthonyMRodrigues** [comment]
I tried to run using pythonenvoperator, but if I do that, my packages are not loaded.
Also tried to run a bash operator installing boto and deps, also don't work,

**Comment by tompizmor** [comment]
Hello @AnthonyMRodrigues,

I just wanted to let you know that we have already identified the issue. We will work on fixing it and release a new revision of the image. I will update this issue once that happens.

**Comment by AnthonyMRodrigues** [comment]
@tompizmor  Thanks very much.
I'll wait for it.

**Comment by tompizmor** [comment]
@AnthonyMRodrigues New images have been released for Airlfow, Airflow Scheduler, and Airflow Worker. The `botocore.docs` module is now included. 

Let me know if it works now!

**Comment by AnthonyMRodrigues** [comment]
Thanks @tompizmor 
I'll check and tell you.

**Comment by NetWeiChen** [comment]
@tompizmor, I am using apache-airflow 1.10.9, and still get "no module named 'botocore'" when I  from airflow.hooks.S3_hook import S3Hook.

Here is requiremetns.txt
apache-airflow[kubernetes]==1.10.9
botocore>=1.12
boto3>=1.9
apache-airflow[s3]>=1.10

**Comment by rafariossaa** [comment]
Hi @NetWeiChen ,
  This issue was close a couple of years ago, do you mind opening a new issue ?
