### ISSUE TITLE
previous change has made certain ldap configurations impossible

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow#102]
**Description**

[this](https://github.com/bitnami/bitnami-docker-airflow/commit/5c440af48bffb9d82d324a8342312cc3d5ac533c#diff-fe52335a3f4514e26da526c375844185e453bee5e854901cb692af7828a37507) change has locked away the ldap configuration option AUTH_LDAP_ALLOW_SELF_SIGNED which has stopped me from moving away from a manually managed webserver_config.py config file 

There is no need for this option to be gated behind TLS conf as there are 2 methods of having encryption on ldap. 
The new change of only being able to use `AUTH_LDAP_ALLOW_SELF_SIGNED` if `AIRFLOW_LDAP_USE_TLS` is Yes breaks the newer encryption method of ldap

**Steps to reproduce the issue:**

1. use an ldaps:// uri (aka modern non StartTLS wrapped connection)
2. airflow will not be able to connect and will give very little log lines

**Describe the results you received:**

```
airflow_1             | [2021-09-21 14:50:23,760] {manager.py:962} DEBUG - LDAP bind indirect TRY with username: '<REMOVED>'
airflow_1             | [2021-09-21 14:50:23,800] {manager.py:1201} ERROR - {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'}
```

**Describe the results you expected:**

ldaps:// uri's to work as it previously did before this change

**Additional information you deem important (e.g. issue happens only occasionally):**

an ldap server with ssl (Non tls) but wanting to ignore self signed cert WITHOUT being forced to supply a cert

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

ubuntu vms. using docker-compose and haproxy as a frontend / loadbalancer

**Comment by ITJamie** [comment]
@Mauraza Any chance of looking at this? I was preparing to move our staging airflow back to autogenerated configuration files after you merged https://github.com/bitnami/bitnami-docker-airflow/pull/101 when i noticed the issue above re LDAP

**Comment by alemorcuq** [comment]
Thanks for reporting this and opening a PR to fix it! Our team is already reviewing it. 

Sorry for the late reply, it looks like this ticket didn't get into our system until your second message.

**Comment by ITJamie** [comment]
@randradas merged this PR a few days ago. There has not been any new images pushed to docker hub since. Any ETA on when this will be live on docker hub?
https://hub.docker.com/layers/bitnami/airflow/2/images/sha256-9c1c51784189cef4dc8f8d497bda818f212cdb872feb84b86593f0d0021ece22?context=explore - 5 days ago

**Comment by alemorcuq** [comment]
Hi, @ITJamie. It looks like some recent changes were causing some issues in our internal pipeline. A new image was released yesterday, could you check that one?

**Comment by ITJamie** [comment]
confirmed and its working as expected now
