### ISSUE TITLE
AIRFLOW_LDAP_ROLES_MAPPING has been made manditory for ldap enabled configs. no examples given

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow#109]
**Description**

AIRFLOW_LDAP_ROLES_MAPPING has been mandatory but no example config has been given.
setting AIRFLOW_LDAP_ROLES_MAPPING="" has allowed bypassing of this option 

**Steps to reproduce the issue:**

1. create docker-compose without AIRFLOW_LDAP_ROLES_MAPPING var

**Describe the results you received:**

setup will fail

**Describe the results you expected:**

previously not required, AIRFLOW_USER_REGISTRATION_ROLE was enough to automap users to a default role.
addition of this feature will be useful, but no example has been given of what the data formatting is needed (is it json, etc).

**Additional information you deem important (e.g. issue happens only occasionally):**

IMHO If AIRFLOW_LDAP_ROLES_MAPPING is not supplied it should default to a blank string and not cause existing installs to fail.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

ubuntu vms. using docker-compose and haproxy as a frontend / loadbalancer

**Comment by alvneiayu** [comment]
hi @ITJamie

It seems that this is a mandatory variable enabling LDAP ([case](https://stackoverflow.com/questions/68536810/airflow-with-ad-auth-stuck-in-a-redirect-loop-at-login)). This variable fixes a redirect loop problem. [Here](https://github.com/bitnami/charts/pull/7484/files) you can find the PR including this variable. It is true that we included LDAP examples in our chart ([here](https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L886)) and also in the chart README ([here](https://github.com/bitnami/charts/blob/master/bitnami/airflow/README.md#airflow-ldap-parameters)). But we didn't include a LDAP example in our container README and it will be really helpful for the community.

I think that it is not a good idea to include it as a blank value. I think that the users will reproduce the same loop problem.

Let me try to include some LDAP example inside this README.

Thanks a lot for your comments and your help.

Álvaro
