### ISSUE TITLE
Azure module on the airflow

### ISSUE THREAD

**Issue by swathiAMD** [bitnami/bitnami-docker-airflow#11]
Hi,

  I have installed the bitnami helm chart to deploy the Airflow on the Azure Kubernetes Service.  I m trying to use the wasb_hook to connect to the Azure blob service. But i get message saying the Azure module is not found. I though this Airflow came with the libraries in it. Now i m not sure how to resolve this issue. Any work around?

**Comment by miguelaeh** [comment]
Hi @swathiAMD ,
I think you need to install it manually. Please, check [this](https://github.com/bitnami/bitnami-docker-airflow/issues/5#issuecomment-502733904) there is a similar workaround there. Let us know if you still having problems after that.
