### ISSUE TITLE
Load Examples Environment Variable

### ISSUE THREAD

**Issue by aaditya-panik** [bitnami/bitnami-docker-airflow#12]
**Description**

Setting the `AIRFLOW_LOAD_EXAMPLES` to `no` doesn't seem to have any effect and the default is used. Am I missing something here?

**Steps to reproduce the issue:**

Same docker-compose.yml file with `airflow-scheduler.environment` having the `AIRFLOW_LOAD_EXAMPLES=no` entry.

**Describe the results you received:**

Example DAGs shipped with Airflow are present in the Airflow UI.

**Describe the results you expected:**

Airflow UI without example DAGs

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Docker version 19.03.1, build 74b1e89
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 37
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: RPLR:KJYC:F5R7:56SB:GBSY:FCTV:RF3E:ZG3D:TES6:NPLQ:2REH:LQKW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 79
  Goroutines: 85
  System Time: 2019-09-04T11:34:54.163986899Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @aaditya-panik, can you add the environment variable in the `airflow-scheduler` service too? Please make sure that you start again from a clean by removing the docker volumes.

**Comment by aaditya-panik** [comment]
Hi @andresbono, I seem to have made a slight mistake in the issue description. I meant to say `airflow-scheduler.environment` and not `airflow.environment`. Thanks for that. I followed the steps again with no volumes and it seems to still show up. Just to make sure I'm not mistaken if I do set `AIRFLOW_LOAD_EXAMPLES=no` in `airflow-scheduler.environment`, when I open the UI there should no preloaded DAGs, correct?

**Comment by andresbono** [comment]
> I followed the steps again with no volumes and it seems to still show up. Just to make sure I'm not mistaken if I do set `AIRFLOW_LOAD_EXAMPLES=no` in `airflow-scheduler.environment`, when I open the UI there should no preloaded DAGs, correct?

That's correct. What we did was:

1) Make sure no volumes are present
```bash
docker-compose down -v
```
2) Modify the `docker-compose.yml` file
```diff
@@ -19,6 +19,7 @@ services:
   airflow-scheduler:
     image: bitnami/airflow-scheduler:1
     environment:
+      - AIRFLOW_LOAD_EXAMPLES=no
       - AIRFLOW_DATABASE_NAME=bitnami_airflow
       - AIRFLOW_DATABASE_USERNAME=bn_airflow
       - AIRFLOW_DATABASE_PASSWORD=bitnami1
@@ -28,6 +29,7 @@ services:
   airflow:
     image: bitnami/airflow:1
     environment:
+      - AIRFLOW_LOAD_EXAMPLES=no
       - AIRFLOW_DATABASE_NAME=bitnami_airflow
       - AIRFLOW_DATABASE_USERNAME=bn_airflow
       - AIRFLOW_DATABASE_PASSWORD=bitnami1
```

3) Start the containers and access the web UI:

```
docker-compose up
```

![image](https://user-images.githubusercontent.com/1057973/64425146-40672f80-d0ab-11e9-817f-f3a65860f607.png)

Make sure you add the en var variable in both containers: `airflow` and `airflow-scheduler`.

**Comment by aaditya-panik** [comment]
Got it, thanks @andresbono ! I think the documentation doesn't include `AIRFLOW_LOAD_EXAMPLES` for `airflow.environment` and only shows under `airflow-scheduler.environment`.

**Comment by andresbono** [comment]
Thanks for noticing, @aaditya-panik. We are going submit a PR with the fix shortly.

**Comment by andresbono** [comment]
Done @aaditya-panik!
