### ISSUE TITLE
AUTH_LDAP_SERVER SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pushkinsk44** [bitnami/bitnami-docker-airflow#121]
Hello!
catching error when deploying Airflow 2.2.2 with LDAP = true
I use the image bitnami/airflow:2.2.2-debian-10-r8

`  File "/opt/bitnami/airflow/webserver_config.py", line 92
    AUTH_LDAP_SERVER = ldaps://ххх.yyy.com:636
                            ^
SyntaxError: invalid syntax`

Having experimented a little, I found out that the reason is in these [changes](https://github.com/bitnami/bitnami-docker-airflow/commit/f1f8b2f8fe67a7d8f8921c14be2973ef398816df#diff-fe52335a3f4514e26da526c375844185e453bee5e854901cb692af7828a37507)  because it works with the previous version of the image bitnami/airflow:2.2.2-debian-10-r7

Apparently quotes are required here
AUTH_LDAP_SERVER = 'ldaps://ххх.yyy.com:636'

**Comment by miguelaeh** [comment]
Hi @pushkinsk44 ,
Could you share how your configuration file ended up? It seems the PR you referenced is setting the `AUTH_LDAP_TLS_CACERTFILE` as a string while it wasn't before.

**Comment by pushkinsk44** [comment]
I don't have a config file because it is generated automatically by libairflow.sh when the airflow-web pod starts.
Since I get an error, the pod does not start and I cannot pull out the resulting config.

It cannot be related to AUTH_LDAP_TLS_ CACERTFILE because tls is disabled.
And the error text clearly indicates the line that caused the error

**Comment by miguelaeh** [comment]
I just saw the issue. The logic seems to be in the wrong order here:
```
is_boolean_yes "$is_literal" && entry="${key} = ${value}" || entry="${key} = '${value}'"
```

**Comment by miguelaeh** [comment]
Closing this as it was fixed some days ago
