### ISSUE TITLE
postgresql_remote_execute: command not found

### ISSUE THREAD

**Issue by izzycodes** [bitnami/bitnami-docker-airflow#123]
**Description**

Hi!

In attempting to get a simple deployment of Airflow working locally, I decided to use Bitnami's instructions for Docker Compose, but was unable to.

**tl;dr**

There seems to be an issue with some of the recent image builds with respect to `libairflow.sh`, but I was able to get the `docker-compose.yml` up and running by reverting to the following images:

- `docker.io/bitnami/airflow:2.2.2-debian-10-r8`
- `docker.io/bitnami/airflow-scheduler:2.2.2-debian-10-r9`
- `docker.io/bitnami/airflow-worker:2.2.2-debian-10-r9`

**Steps to reproduce the issue:**

1. Follow the **TL;DR** instructions on the **master** branch `README.md`
2. Watch the logs

**Describe the results you received:**

```
...
airflow-scheduler_1  | /opt/bitnami/scripts/libairflow.sh: line 434: postgresql_remote_execute: command not found
airflow-worker_1     | /opt/bitnami/scripts/libairflow.sh: line 434: postgresql_remote_execute: command not found
airflow-scheduler_1  | airflow-scheduler 20:49:53.30 ERROR ==> Could not connect to the database
airflow-worker_1     | airflow-worker 20:49:53.35 ERROR ==> Could not connect to the database
airflow_airflow-scheduler_1 exited with code 1
airflow_airflow-worker_1 exited with code 1
```

The other services spin up successfully, and am able to log into the Airflow UI, but it outputs the (as expected in this case) *"scheduler isn't running"* notice on the dags page.

**Describe the results you expected:**

As it is the "starter" instructions, would expect all the services to spin up successfully.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for MAC.

At the time of running `docker-compose up`, the `2` image tag corresponds to the following:

- `2.2.2-debian-10-r17` on **airflow-worker**
- `2.2.2-debian-10-r17` on **airflow-scheduler**
- `2.2.2-debian-10-r8` on **airflow**

**Comment by tekon92** [comment]
same issue happened to me, @izzycodes do you find any updates ?

**Comment by izzycodes** [comment]
> same issue happened to me, @izzycodes do you find any updates ?

Hey @tekon92 , in poking around in the code (specifically [libadmin.sh](2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh) ) I don't see the offending line, so am unsure of a PR. However, was able to run it by changing the image tag in the `docker-compose.yaml` to:

**Comment by javsalgar** [comment]
Hi,

Which is the libadmin.sh file that you are referring to? Do you mean libairflow.sh?

**Comment by aalemanq** [comment]
> > same issue happened to me, @izzycodes do you find any updates ?
> 
> Hey @tekon92 , in poking around in the code (specifically `libadmin.sh` ) I don't see the offending line, so am unsure of a PR. However, was able to run it by changing the images in the `docker-compose.yaml` to:
> 
> (oooops hit post before I finished)
> 
>     * `docker.io/bitnami/airflow:2.2.2-debian-10-r8`
> 
>     * `docker.io/bitnami/airflow-scheduler:2.2.2-debian-10-r9`
> 
>     * `docker.io/bitnami/airflow-worker:2.2.2-debian-10-r9`

This helps me a lot
