### ISSUE TITLE
spark_default connection indicates Amazon Web Services for Connection Type

### ISSUE THREAD

**Issue by willim32533** [bitnami/bitnami-docker-airflow#125]
The Edit Connection page indicates "Amazon Web Services" for the Connection Type of spark_default.  What should the connection type be for hosting spark and airflow locally?

**Comment by carrodher** [comment]
For information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by willim32533** [comment]
My apologies, thank you for your feedback.  I have subsequently posted the question to the Airflow repo discussion board.
