### ISSUE TITLE
Helm help deploying to EKS

### ISSUE THREAD

**Issue by maccaveli6** [bitnami/bitnami-docker-airflow#127]
I have the latest helm airflow working locally and can access the web-ui using port forwarding.  what configurations are needed to deploy this on EKS?  What is the recommended way to access the UI in production?

Thanks!

**Comment by javsalgar** [comment]
Hi,

Please note that we don't provide this kind of consulting services. The best settings may depend on your platform and the requirements of your company (some use LoadBalancer, others Ingress...). In any case, we will leave the ticket open to see if someone from the community wants to participate.

**Comment by maccaveli6** [comment]
I have tried using LoadBalancer on the web service.  When I tried to connect directly, I got a message that says Airflow is not here, informative, but not useful.   
I have tried using Ingress controller.  Don't exactly know how to configure it to work with this.  

@javsalgar - your message is equally useful as the airflow message.   

Does anyone have any useful info on how to actually get the web frontend plugged in when not working in a local environment?

Thanks!

**Comment by javsalgar** [comment]
Hi,

Just to confirm, when you set the service to LoadBalancer you get some extra instructions in order to update the release in order to complete the deployment. Did you follow them? You can check them by running `helm status <name_of_your_release>`
