### ISSUE TITLE
each restart sets up default connections

### ISSUE THREAD

**Issue by electrical** [bitnami/bitnami-docker-airflow#128]
**Description**

We've noticed that with each restart of airflow ( i suspect the web instance ) all defaults get setup including default connections.

**Steps to reproduce the issue:**

1. install airflow
2. Remove existing connections and add own
3. Restart webserver
4. See all default connections returned

**Describe the results you received:**

Default connections are added to the list again

**Describe the results you expected:**

Use data that is in the database since the application is already initialized

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

```
Tue, Jan 25 2022 12:14:39 pm | irflow 12:14:39.41 INFO ==> ** Starting Airflow setup **
Tue, Jan 25 2022 12:14:39 pm | airflow 12:14:39.42 INFO ==> Validating settings in POSTGRESQL_CLIENT_* env vars
Tue, Jan 25 2022 12:14:39 pm | airflow 12:14:39.46 INFO ==> Initializing Airflow ...
Tue, Jan 25 2022 12:14:39 pm | airflow 12:14:39.48 INFO ==> No injected configuration file found. Creating default config file
Tue, Jan 25 2022 12:14:41 pm | airflow 12:14:41.24 INFO ==> Configuring Airflow webserver authentication
Tue, Jan 25 2022 12:14:41 pm | airflow 12:14:41.26 INFO ==> Configuring Airflow database
Tue, Jan 25 2022 12:14:41 pm | airflow 12:14:41.33 INFO ==> Configuring Celery Executor
Tue, Jan 25 2022 12:14:41 pm | airflow 12:14:41.37 INFO ==> Trying to connect to the database server
Tue, Jan 25 2022 12:15:29 pm | airflow 12:15:29.56 INFO ==> Populating database
Tue, Jan 25 2022 12:15:34 pm | airflow 12:15:34.58 INFO ==> Creating Airflow admin user
Tue, Jan 25 2022 12:15:41 pm | airflow 12:15:41.66 INFO ==> Persisting Airflow installation
Tue, Jan 25 2022 12:15:41 pm | airflow 12:15:41.71 INFO ==> ** Airflow setup finished! **
```

**Comment by javsalgar** [comment]
Hi,

Could you confirm you are using persistent volumes in the installation? Which is the Kubernetes Cluster you are using?

**Comment by electrical** [comment]
Hi, we aren't using any persistent volume. All data is stored in Postgres which I presumed was enough?
Also the airflow helm chart does not provide any persistence for the web instance

**Comment by juan131** [comment]
Hi @electrical 

> we aren't using any persistent volume. All data is stored in Postgres which I presumed was enough?

That's not enough, Airflow containers also need to persist some data/configuration. Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-airflow#persisting-your-application

**Comment by electrical** [comment]
@juan131 The airflow helm chart seems to indicate something else:

https://github.com/bitnami/charts/tree/master/bitnami/airflow#persistence

Also, the helm chart doesn't provide any persistence of data.
Is this a major discrepancy in functionality?

**Comment by juan131** [comment]
Hi @electrical 

As you can see in [this code block](https://github.com/bitnami/bitnami-docker-airflow/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L114-L147), the behavior is different when it detect there's existing data:

- No existing data: It initialize the PostgreSQL database and it creates the admin user and pool. Then, it persists the data.
- Existing data: It simply upgrade the database schema.

**Comment by electrical** [comment]
@juan131 I understand the process.
But if this is what's being expected, I don't understand why the helm chart doesn't provide the functionality to persist the data.

**Comment by juan131** [comment]
You're completely right.. There's sth we're missing here but the setup we have in the chart doesn't make much sense to me since it's not respecting the existing database when Airflow pods are recreated. 

Indeed I came across with this issue where @randradas also mentioned a race conditions issue when running multiple Airflow web replicas that seems to be related with the same thing:

- https://github.com/bitnami/charts/issues/7178

**Comment by electrical** [comment]
I do wonder what data needs to be persisted. So far with each restart everything is working fine since all data is stored in the postgres database anyway.
The only "issue" i'm seeing right now is that the setup is run which sets up the default connections.
Shouldn't it be enough to check if the database is initialised?

**Comment by juan131** [comment]
@electrical FYI check the comment I just shared in the PR below describing my proposal to address this issue:

- https://github.com/bitnami/charts/pull/7855#issuecomment-1027982058

**Comment by electrical** [comment]
Shared writable storage is quite limited in options. CephFS and NFS come to mind, most likely there are more.
This still doesn't solve the issue I'm having since I only have a single web container instance.

I don't understand what kind of data the web instance needs to persist on the filesystem while all relevant data is in the database.

**Comment by juan131** [comment]
Hi @electrical 

FYI: As an alternative to NFS, I'm also considering using an init-container on every replica that check the existence of the required tables in the database and use this as the "semaphore" to skip populating it. Expect updates on this topic soon.

**Comment by juan131** [comment]
Hi @electrical 

Please check my last comment at https://github.com/bitnami/charts/issues/7178 that also address this specific issue.

**Comment by electrical** [comment]
@juan131 I can confirm this solved our issue. Thank you!
