### ISSUE TITLE
Enable sentry integration

### ISSUE THREAD

**Issue by creyD** [bitnami/bitnami-docker-airflow#131]
### Name and Version

latest version

### What is the problem this feature will solve?

Currently it is not possible with this image to enable the sentry integration. Even though one can set the `AIRFLOW_SENTRY_DSN` env variable it doesn't do anything because the sentry integration is not installed as in https://docs.sentry.io/platforms/python/guides/airflow/

### What is the feature you are proposing to solve the problem?

This would probably need to be a check if the variable is set and if yes, then it installs the sentry dependency with airflow.

### What alternatives have you considered?

I tried manually adding it after the fact, but it didn't work. You could manually add sentry to every DAG file, but this is time consuming and unnecessary, as Airflow supports this feature out of the box.

**Comment by marcosbc** [comment]
Hi @creyD, unfortunately this is not a feature we are planning to support.

Note that you can install extra dependencies to the Airflow container as specified in the README: [Installing additional python modules](https://github.com/bitnami/bitnami-docker-airflow#installing-additional-python-modules).

With that, you should be able to configure Sentry without problems. If you find that something else is missing, like some configurations options or so, feel free to contribute any improvements to the README or configuration via a PR! We would be happy to review it.

**Comment by creyD** [comment]
Thanks, however installing sentry after the fact + setting the sentry env var doesn't appear to work, as our sentry get's no issues. We have to add it to every flow now.
