### ISSUE TITLE
Overriding airflow settings does not work

### ISSUE THREAD

**Issue by cccs-jc** [bitnami/bitnami-docker-airflow#14]
I'm following the example in the README file. It says you can override the airflow configuration by specifying an environment variable AIRFLOW__<SECTION>__<KEY> with the two underscores around the section. I've followed the instructions

docker run -d --name airflow -p 8080:8080 \
    -e AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho= \
    -e AIRFLOW_EXECUTOR=CeleryExecutor \
    -e AIRFLOW_DATABASE_NAME=bitnami_airflow \
    -e AIRFLOW_DATABASE_USERNAME=bn_airflow \
    -e AIRFLOW_DATABASE_PASSWORD=bitnami1 \
    -e AIRFLOW_PASSWORD=bitnami123 \
    -e AIRFLOW_USERNAME=user \
    -e AIRFLOW_EMAIL=user@example.com \
    -e AIRFLOW__SMTP__SMTP_HOST=smtp@gmail.com \
    -e AIRFLOW__SMTP__SMTP_USER=your_email@gmail.com \
    -e AIRFLOW__SMTP__SMTP_PASSWORD=your_password \
    -e AIRFLOW__SMTP__SMTP_PORT=587 \
    --volume airflow_data:/bitnami \
    bitnami/airflow:latest

However when I go into the container the /opt/bitnami/airflow/airflow.cfg does contain any of these overrides.

/opt/bitnami/airflow$ egrep -R 'your_password' .
no matches

thanks

**Comment by marcosbc** [comment]
Hi @cccs-jc, we have been able to reproduce your issue.

At first I cannot see why this is not working, as the environment variables should be detected by Airflow, which is in charge of setting the configuration for the initial configuration file, as mentioned in the official [documentation](https://airflow.apache.org/howto/set-config.html). Therefore this needs additional investigation.

I've created an internal task for looking into this issue, but unfortunately I cannot give an ETA for when we expect this to be fixed.

**Comment by cccs-jc** [comment]
Thanks, looking forward to the fix

**Comment by chrisbeach** [comment]
I'm also finding that overriding settings has no effect e.g.

    environment:
        - AIRFLOW_LOAD_EXAMPLES=no

(I have tried applying this to all three of airflow, worker and scheduler). Still the examples are loaded.

**Comment by andresbono** [comment]
Hi @chrisbeach, can you take a look at this issue? https://github.com/bitnami/bitnami-docker-airflow/issues/12. It may be useful for you.

**Comment by chrisbeach** [comment]
Thanks @andresbono - that fixed it for me.

**Comment by alfonsodg** [comment]
Any update with this?? 

I can share something:
You can add plugins mounting also:
/opt/bitnami/airflow/plugins:MOUNT_POINT
If you use celery, the mount point needs to be in the worker and scheduler also and finally restarts the service to start using the plugins

**Comment by andresbono** [comment]
Hi @alfonsodg, we couldn't address the issue yet. If you give us more details on your specific issue, that will be useful for us.

**Comment by dwardu89** [comment]
Hi @marcosbc  has there been any progress on this? I was trying to figure out why there is an `airflow-inputs.json` file which i think might be causing the env var overrides to be ignored.

**Comment by marcosbc** [comment]
Hi @dwardu89, unfortunately we had not been able to spend any time on this yet. However, I've just re-evaluated this issue now and it looks like the container works properly.

After checking the AirFlow initialization logic, it looks like you have two ways of setting the configurations:

* Via the configuration file
* Via environment variables (AIRFLOW__...)

However, setting the environment variables **does not** set the value in the configuration file, but they will be considered with higher priority than any entry in the configuration file at runtime. I could also check that this is the same behavior as in https://github.com/puckel/docker-airflow/.
