### ISSUE TITLE
Connection to Oracle

### ISSUE THREAD

**Issue by MichaelJDrK** [bitnami/bitnami-docker-airflow#16]
**Description**

In airflow I want to connect to a Oracle DB, so I need the Oracle Instant client in the Image as well as the necessary apache-airflow oracle python modules.

How do I add missing dependencies? There is no documentation whats the official way to do that.

**Comment by andresbono** [comment]
Hi @MichaelJDrK, can you point us to Airflow documentation where this is explained so we can try to adapt the steps to the container?

**Comment by kpa92** [comment]
Hi,

I had a simmilar issue with the puckel/docker-airflow image. My solution was to install the oracle client inside the docker container. Probably, you could do the same with this image too.

This website was really helpful for me: http://mritjudge.com/linux/install-oracle-instant-client-on-ubuntu-linux/

And here is the relevant part from my Dockerfile. I hope it helps:

```
# Install oracle client
# http://mritjudge.com/linux/install-oracle-instant-client-on-ubuntu-linux/

COPY oracle_client/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm /tmp/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
COPY oracle_client/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm /tmp/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
COPY oracle_client/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm /tmp/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
RUN apt-get update && apt-get install -y alien
RUN alien -i /tmp/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm &&\ 
    alien -i /tmp/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm &&\ 
    alien -i /tmp/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
    
    
RUN apt-get install libaio1
ENV LD_LIBRARY_PATH /usr/lib/oracle/12.2/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
ENV ORACLE_HOME /usr/lib/oracle/12.2/client64
ENV PATH $PATH:$ORACLE_HOME/bin
RUN ln -s /usr/include/oracle/12.2/client64 $ORACLE_HOME/include

```

**Comment by andresbono** [comment]
Hi @kpa92, thanks for the information. Will you give it a try, @MichaelJDrK?

**Comment by danielc103** [comment]
Having the same issue and wondering if this is the "official" answer?

**Comment by andresbono** [comment]
Hi @danielc103, @kpa92 kindly shared a solution that worked for him, but we haven't received confirmation from other users. If you test it, please share with us if it works for you too.

**Comment by danielc103** [comment]
sorry, yes I was successful in installing the client using @kpa92 example.

**Comment by andresbono** [comment]
Great, @danielc103, thanks for confirming!
