### ISSUE TITLE
Using kubeapps and installing python dependencies

### ISSUE THREAD

**Issue by olsw** [bitnami/bitnami-docker-airflow#18]
**Description**

I have used kubeapps to install airflow but some of the plugins i need to install require that pip is used. There doesnt seem to be a way to easily get this in place using kubeapps. Is the recommendation therefore to create my own version of the Dockerfile and not use kubeapps? Or is there a way to make my own versions but still use kubeapps? Documentation still seems quite sparse on this

**Comment by javsalgar** [comment]
Hi,

I think that the solution lies in allowing custom init scripts so you can use more complex logic (such as installing pip). If we allow that, you could still use kubeapps without issues.

If you do not want to wait and want to create your custom image, you can still use kubeapps by changing the values.yaml file (advanced mode) and setting a different image.

**Comment by olsw** [comment]
Yes custom init scripts would be great but sounds like i should build the images for now.
Stupid question time - how do i get into advanced mode?

**Comment by javsalgar** [comment]
Hi,

In this guide you can see how the values.yaml file is edited https://docs.vmware.com/en/VMware-Cloud-Marketplace/services/user-guide/GUID-368B72D0-A84E-46A9-AE2C-5F2D73F55C47.html
