### ISSUE TITLE
Where are the data and where to store my dags?

### ISSUE THREAD

**Issue by 5amfung** [bitnami/bitnami-docker-airflow#2]
**Description**

I can't quite figure out where all the data are stored and where I should put my dags.  I following the instruction at https://github.com/bitnami/bitnami-docker-airflow#persisting-your-application to most host directories as data volumes.  I expect the postgres, redis, and airflow log and data would be stored at there, but that wasn't the case.  

**Steps to reproduce the issue:**

1. git clone project
2. Change volume in `docker-compose.yml` as such:
```
volumes:
      - ./mydata:/bitnami
```
3. Run `docker-compose up`

**Describe the results you received:**

The directories are empty after `docker-compose up` and even though airflow was functioning properly.

**Describe the results you expected:**

I don't expect the directories to be empty.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```

- Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 49
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: UTNP:IY76:7NH5:3CZ4:QSRB:Z5SB:CV2Y:3XG3:4FYD:U6SD:L3CO:2MOG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 54
 System Time: 2019-05-19T19:16:30.2911436Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @5amfung.

What data do you expect to be persisted from Airflow? This container persists the `/opt/bitnami/airflow/data` directory, but it's empty by default.

Regarding your dags, you should mount them to `/opt/bitnami/airflow/dags`. We will make sure to document that.

Regards,
Alejandro

**Comment by 5amfung** [comment]
@alemorcuq For example, I want to persiste the data from Postgres database.

Also if I want to change the configuration of Airflow, how and where do it access `airflow.cfg`?  I don't think the documentation is clear on that.  I know I could do some digging to figure it all out, but that would probably take me some time to do it.

Thank you.

**Comment by 5amfung** [comment]
Also where do I access the airflow log?  `/opt/bitnami/airflow/logs`?

**Comment by alemorcuq** [comment]
Hi, @5amfung.

To persist the data from the Postgresql database, you have to mount your volume to the `/bitnami/postgresql` directory. We are in the process of updating our documentation to reflect that.

You can find the `airflow.cfg` file under `/opt/bitnami/airflow/airflow.cfg`, and the `logs` directory under `/opt/bitnami/airflow/logs`. You can access them by accessing the container. For example:

```
$ docker exec -it MY_AIRFLOW_CONTAINER bash
```

The logs can also be accessed through the `docker` command line:

```
$ docker logs MY_AIRFLOW_CONTAINER
```

Finally, regarding the `airflow.cfg` file, you can mount your own file to the location I mentioned earlier or configure it using environment variables. From the README:

> In addition to the previous environment variables, all the parameters from the configuration file can be overwritten by using environment variables with this format: `AIRFLOW__{SECTION}__{KEY}`. Note the double underscores.

Regards,
Alejandro
