### ISSUE TITLE
How is airflow.cfg generated?

### ISSUE THREAD

**Issue by cccs-cat001** [bitnami/bitnami-docker-airflow#21]
**Description**

Not so much an issue, more of a question. I was wondering how the airflow.cfg file is generated. When I run airflow on my own machine, it's created automatically with default values and is commented on each line, but whenever I run this image (or any of the other airflow images) It's not that cfg, it seems to be a pre-made one that gets populated with bitnami specific settings. Can anyone explain how it gets generated for me?

**Comment by sameersbn** [comment]
@cccs-cat001 The container executes the `/opt/bitnami/airflow/venv/bin/airflow initdb` which generates the configuration. This command gets executed from the  `nami_initialize airflow` command from the  `app-entrypoint.sh` script.

If you are interested in digging deeper into the module initialisation logic, take a look at the contents of `/.nami/components/com.bitnami.airflow` folder in the airflow container.
