### ISSUE TITLE
Hard-coded env vars, including passwords [BUG] [SECURITY]

### ISSUE THREAD

**Issue by mirekphd** [bitnami/bitnami-docker-airflow#22]
We have hard-coded environment variables problem here. For instance try changing all occurences of "bitnami1" to "bitnami2" in the [`docker-compose.yml`](https://raw.githubusercontent.com/bitnami/bitnami-docker-airflow-scheduler/master/docker-compose.yml) and then start this config with `docker-compose` and you will see that Airflow cannot connect to PostgreSQL, because password has been hard-coded in the [Dockerfile here](https://github.com/bitnami/bitnami-docker-airflow/blob/master/1/debian-9/Dockerfile) and there is no startup script to change it, so the password change is effective only in the postgres container, resulting in passwords mismatch and the inability to connect.

Error message from the `bitnami/airflow` container log:
```
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
[..]
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
Error executing 'postInstallation': Cannot connect to PostgreSQL server:
psql: FATAL:  password authentication failed for user "bn_airflow"
```

More worryingly perhaps, this problem applies also to web interface default admin credentials, which cannot be changed from these values hard-coded in the Dockerfile:
```
AIRFLOW_USERNAME="user"
AIRFLOW_PASSWORD="bitnami"
```

Related: #14

**Comment by dani8art** [comment]
Hi @mirekphd 

I'm not able to reproduce it, let me try a bit more, I will come back to you soon. Could you check #12 while I'm checking your issue in my environment?

Thank you!
Regards.

**Comment by dani8art** [comment]
Hi @mirekphd 

- Did you try  #12?

I would say that you are missing to remove the persistent volume so the password doesn't change, please try to execute `docker-compose down -v`. Before removing volumes, you have to make sure that you are doing a backup of your data, otherwise, you will lose it. 

Regards.
