### ISSUE TITLE
[FEATURE REQUEST] Improve documentation process

### ISSUE THREAD

**Issue by aissarmurad** [bitnami/bitnami-docker-airflow#25]
**Description**

Bitnami Apache Airflow images are poorly documented.

**Describe the results you received:**

The Bitnami Apache Airflow images are poorly documented
and I did not found an easy way to contribute.

**Describe the results you expected:**

It would be great if the documentation would be versioned and use markdown.

**Comment by javsalgar** [comment]
Hi,

The documentation is located in the README.md file in this repository. It uses markdown and is open to Pull Requests. Could you let us know which sections you are currently missing?
