### ISSUE TITLE
Permission issues getting bitnami-docker-airflow working on IBM k8s

### ISSUE THREAD

**Issue by stevenwarejones** [bitnami/bitnami-docker-airflow#30]
I'm trying to get these Bitnami charts working on IBM Cloud k8s. I'm getting the following error on the redis-master pod
```
 17:44:11.65 INFO  ==> ** Starting Redis **
1:C 29 Feb 2020 17:44:11.655 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Feb 2020 17:44:11.655 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Feb 2020 17:44:11.655 # Configuration loaded
1:M 29 Feb 2020 17:44:11.657 # Can't open the append-only file: Permission denied
```

Eventually, of course, the liveness probe fails
`Liveness probe failed: 127.0.0.1:5432 - rejecting connections`

**Comment by miguelaeh** [comment]
Hi @stevenwarejones ,
The `appendonly.aof` file should be into the `/data` directory, that directory is a volume and the Redis container is a non-root container. Did you set the `fsGroup` to `1001` to configure the permissions for that volume? It is done by default so if you didn't change it it should be correct. 
Also, could you provide the exact command you are using to deploy the Chart?

**Comment by beltran-rubo** [comment]
Hi @stevenwarejones we tested Airflow in IBM (latest version) and the application is working well. We also checked Redis master log and we can not reproduce the error you posted. Could you try the latest version again? Did you specify any options for the deployment?

```
07:59:21.99 INFO  ==> ** Starting Redis **
1:C 18 Mar 2020 07:59:22.000 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Mar 2020 07:59:22.000 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Mar 2020 07:59:22.000 # Configuration loaded
1:M 18 Mar 2020 07:59:22.002 * Running mode=standalone, port=6379.
1:M 18 Mar 2020 07:59:22.002 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 18 Mar 2020 07:59:22.002 # Server initialized
```
