### ISSUE TITLE
Adding external modules for some plugins

### ISSUE THREAD

**Issue by alfonsodg** [bitnami/bitnami-docker-airflow#31]
Hi,

Some plugins requires external modules, for example: clickhouse plugin needs clickhouse-driver, i can run inside the deployed container and install the library, however i wanna persist the module, right now i can mount the installed dir inside /opt/bitnami/python/lib/python3.6/site-packages as hardcoding trick but maybe can be a nicer way to do that

**Comment by miguelaeh** [comment]
Hi @alfonsodg ,
Could you let us know more about your use case so we can take a look?

**Comment by alfonsodg** [comment]
Yes!


Airflow is very particular because it allows integration with any other service or databases, in many cases this requires installing new modules.
In our case we need the clickhouse-driver and my solution has been to install it inside the container, the problem is the persistence of the module and for this the only solution was to "assemble" the generated directories of site-packages, a solution not very elegant but that works. It would be appropriate to make a mechanism similar to what is done in / opt / bitnami / airflow / dags that allows cutomized dags, so that users do not have to build the container.
By the way, on ticket  https://github.com/bitnami/bitnami-docker-airflow/issues/30  I indicate how to extend the documentation to add plugins, even though the ideal would be as with / dags and we do not have to restart services
I tried to make the corrections but I saw that the repository does not contain at a glance how it builds the configuration files and other aspects

**Comment by miguelaeh** [comment]
Hi @alfonsodg ,
Thank you very much for the explanation.
Are you deploying the application using docker-compose? I think you can mount a volume in whichever directory you need and that will make that data persistent. So, if I am not wrong you are trying to persist the `site-packages` directory,  can you give a try to mount a volume there?

**Comment by jloehel** [comment]
Can anyone please re-open this issue. I don't like the idea of creating a volume for site-packages. It should be possible to add a `requirements.txt` as a volume to install all necessary modules. Like here:

https://github.com/puckel/docker-airflow/blob/bed777970caa3e555ef618d84be07404438c27e3/script/entrypoint.sh#L26-L29

**Comment by miguelaeh** [comment]
Hi @jloehel ,
We would appreciate if you can open a new issue with the same information as a feature request.
Regards.

**Comment by jloehel** [comment]
> Hi @jloehel ,
> We would appreciate if you can open a new issue with the same information as a feature request.
> Regards.

Done: https://github.com/bitnami/bitnami-docker-airflow/issues/32

**Comment by miguelaeh** [comment]
Thanks!
