### ISSUE TITLE
Adding external modules for some plugins

### ISSUE THREAD

**Issue by jloehel** [bitnami/bitnami-docker-airflow#32]
Hello Bitnami Team,

I'd like to request a new feature for this docker image. Some plugins need additional python modules. I would like to avoid rebuilding the image for this case. I would prefer a mechanism to inject those modules into the image.

Matthieu Roisil uses for his airflow-docker setup a docker volume which holds a `requirements.txt` file.

> https://github.com/puckel/docker-airflow/blob/bed777970caa3e555ef618d84be07404438c27e3/script/entrypoint.sh#L26-L29

Can you please implement something similar. Thanks in advance

**Comment by beltran-rubo** [comment]
Thanks @jloehel for the suggestion.  Ideally those plugins should be already added in the container image but that would require to maintain your own image.

Your proposed solution makes sense for us to simplify how to add plugins to the Airflow solution. We will add to our todo list and let you know when it is ready. Any Pull Requests will be also welcome if you want to speed up that process.

**Comment by marcosbc** [comment]
I'm adding the on-hold label for now so this doesn't get closed until the change is merged.
