### ISSUE TITLE
Upgrade to 1.10.10

### ISSUE THREAD

**Issue by mustela** [bitnami/bitnami-docker-airflow#37]
Hey guys, I see the worker has been updated to 1.10.10, is there any plan to do that with this image? 

Thanks

**Comment by beltran-rubo** [comment]
Hi @mustela we are finding issues in our automated testing with the new version. We are working on checking that everything works correctly before releasing it. Thanks for reporting it.

**Comment by beltran-rubo** [comment]
It has been released today. Keep us in the loop if you have any questions or suggestions, thanks!
