### ISSUE TITLE
Unable to trigger a dag from minikube airflow

### ISSUE THREAD

**Issue by saranyaeu2987** [bitnami/bitnami-docker-airflow#39]
**Description**

**Steps to reproduce the issue:**

1. helm install <name> bitnami/airflow \
   --set airflow.cloneDagFilesFromGit.enabled=true \
   --set airflow.cloneDagFilesFromGit.repository=<github_repo> \
   --set airflow.cloneDagFilesFromGit.branch=master \
   --set airflow.cloneDagFilesFromGit.interval=60
2. login airflow web UI
3. trigger dag

**Describe the results you received:**

-------------------------------------------------------------------------------
Node: selumalai-airflow-web-6b8b68f6cd-97qw7
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/decorators.py", line 121, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/decorators.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/www_rbac/views.py", line 1050, in trigger
    external_trigger=True
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)

**Describe the results you expected:**

Running a dag

**Additional information you deem important (e.g. issue happens only occasionally):**

unable to view the dag in Airflow webserver - it says **_DAG "selumalai_trigger_controller_dag" seems to be missing._**

**Version**
minikube version: v1.9.2
[logs-from-airflow-web-in-selumalai-airflow-web-6b8b68f6cd-97qw7.txt](https://github.com/bitnami/bitnami-docker-airflow/files/4520179/logs-from-airflow-web-in-selumalai-airflow-web-6b8b68f6cd-97qw7.txt)
<img width="1671" alt="Screen Shot 2020-04-22 at 11 13 01 PM" src="https://user-images.githubusercontent.com/19850718/80058443-e2c70c80-84ee-11ea-840f-ef87167e2b09.png">
<img width="1636" alt="Screen Shot 2020-04-22 at 11 13 14 PM" src="https://user-images.githubusercontent.com/19850718/80058450-e5296680-84ee-11ea-8f9a-4c25053b38da.png">

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by saranyaeu2987** [comment]
[logs-from-airflow-web-in-selumalai-airflow-web-6b8b68f6cd-97qw7.txt](https://github.com/bitnami/bitnami-docker-airflow/files/4520187/logs-from-airflow-web-in-selumalai-airflow-web-6b8b68f6cd-97qw7.txt)

**Comment by Mauraza** [comment]
Hi @saranyaeu2987,

could you try adding the `--set airflow.baseUrl=http://127.0.0.1:8080`?
```
helm install bitnami/airflow
--set airflow.cloneDagFilesFromGit.enabled=true
--set airflow.cloneDagFilesFromGit.repository=<github_repo>
--set airflow.cloneDagFilesFromGit.branch=master
--set airflow.cloneDagFilesFromGit.interval=60
--set airflow.baseUrl=http://127.0.0.1:8080
```

**Comment by saranyaeu2987** [comment]
Mauraza,
Thanks a lot. that worked!! :)
I have few more questions. Can you please guide me ?

1. What property should I use to expose the airflow config? I couldnt find in https://github.com/bitnami/charts/tree/master/bitnami/airflow#load-dag-files

2. Is there a command to trigger a job instead of doing it in Airflow webserver UI ?

3. Is it possible to load dags from GitLab instead of GitHUB ? 

4. To load  dags from local machine (in folder File/Dags) what command should I need to use.

Is there a forum or FAG page where can I find answers to all above questions.

**Comment by Mauraza** [comment]
Hi @saranyaeu2987 

1.- Are you  using the [options 3](https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-3-get-your-dag-files-from-a-git-repository)? this could help [documentation](https://docs.bitnami.com/tutorials/deploy-apache-airflow-kubernetes-helm/)

2.- you can trigger a job with the CLI, you can visit de [official documentation ](https://airflow.apache.org/docs/stable/cli-ref.html#trigger_dag)

3.- Is a git repository so yes you can use GitLab

4.- You have to use the [option 1](https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-1-load-locally-from-the-files-folder)

**Comment by saranyaeu2987** [comment]
1 - I am looking for this property. I wanted to expose config
AIRFLOW__WEBSERVER__EXPOSE_CONFIG

will it be **airflow.webserver.expose_config=true** ?

**Comment by Mauraza** [comment]
Hi @saranyaeu2987,

you can find all the parameters of the char in the [README.md](https://github.com/bitnami/charts/tree/master/bitnami/airflow#parameters) I can't find `airflow.webserver.expose_config`

**Comment by saranyaeu2987** [comment]
Hi @Mauraza 
I read the README.md.  I couldnt find property to expose the config via bitami airflow. thats why asked that question. Do you know what would be the property to expose the config in UI ?

**Comment by Mauraza** [comment]
Hi @saranyaeu2987,

You need to use the` airflow.configurationConfigMap` to change that property because you need to edit the `airflow.cfg`.
