### ISSUE TITLE
Enable specific sslmode and portnumber in run.sh file

### ISSUE THREAD

**Issue by ThomasUllrich666** [bitnami/bitnami-docker-airflow#40]
If you are useing an external PG DB then please add a feature to use a custom Port and SSLmode.

Please change the command from this:

if PGPASSWORD=$AIRFLOW_DATABASE_PASSWORD psql -h "$AIRFLOW_DATABASE_HOST" -U "$AIRFLOW_DATABASE_USERNAME" -d "$AIRFLOW_DATABASE_NAME" -c "" > /dev/null ; then
...

to something like this:
if PGPASSWORD=$AIRFLOW_DATABASE_PASSWORD psql "host=$AIRFLOW_DATABASE_HOST dbname=AIRFLOW_DATABASE_NAME user=AIRFLOW_DATABASE_USERNAME sslmode=AIRFLOW_DATABASE_SSLMODE port=AIRFLOW_DATABASE_PORT" -c "" > /dev/null ; then
...

**Comment by andresbono** [comment]
Hi @ThomasUllrich666, thanks for suggesting this change. Would you like to open a PR? Contributions are more than welcome!
