### ISSUE TITLE
Cannot view environment connections/variables in web server

### ISSUE THREAD

**Issue by ze-correia** [bitnami/bitnami-docker-airflow#41]
**Description**

I'm not sure if this is the place to ask, but maybe you can help me. I'm using this your Docker compose file and images to setup Airflow for local development.

I want to have default connections and variables, and I'm setting them up using environment variables as described [here](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#storing-a-connection-in-environment-variables) and [here](https://airflow.readthedocs.io/en/stable/concepts.html#storing-variables-in-environment-variables).

This is working (the connections are available in my DAGs), but I cannot see them in the web server (Admin > Connections). Any ideas how this could be fixed or alternative ways to setup default connection/variables?

**Steps to reproduce the issue:**

1. Add an environment variable for a connection or Airflow variable as described [here](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#storing-a-connection-in-environment-variables) and [here](https://airflow.readthedocs.io/en/stable/concepts.html#storing-variables-in-environment-variables)
2. Start Airflow (`docker-compose up` etc)
3. Access the web server and go to the connections/variables list via the menu (e.g. Admin > Connections)

**Describe the results you received:**

Added connection/variable is not visible

**Describe the results you expected:**

Added connection/variable is visible and editable

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.846GiB
 Name: docker-desktop
 ID: N37N:WB5X:J2JA:LTJB:27HY:B5S3:2M73:L2SY:D57M:DGF6:IHHI:BTI5
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 79
  Goroutines: 91
  System Time: 2020-05-13T17:13:21.7726333Z
  EventsListeners: 5
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by dani8art** [comment]
- Regarding variables as far as I read in the [docs](https://airflow.readthedocs.io/en/stable/concepts.html#variables).

> Variables can be listed, created, updated and deleted from the UI (Admin -> Variables), code or CLI.

It says that you can store them in the environment vars and use it from the scripts, I guess you should add a script where you then `create` the environment var in to the UI.

- Regarding connection as far as I read in the [docs](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#managing-connections) you can [create from ui](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#creating-a-connection-with-the-ui) and [create from cli](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#creating-a-connection-with-the-ui) but only store them in [env vars](https://airflow.readthedocs.io/en/stable/howto/connection/index.html#storing-a-connection-in-environment-variables)

I think you should create a script to add this new connection to the UI.

**Comment by ze-correia** [comment]
Thanks for the quick feedback!

So, if I understand correctly, I guess the best option to have some default variables and connections available in the UI on `up` would be to override the entrypoint and make sure to create them using the CLI, right?

**Comment by dani8art** [comment]
I would say yes, At least it is what the doc says. Also, you could try to have a DAG doing this kind of thing and load it as [https://github.com/bitnami/bitnami-docker-airflow#load-dag-files](https://github.com/bitnami/bitnami-docker-airflow#load-dag-files). Then, execute it from the UI and see if the env vars and connections appear in the UI.

**Comment by ze-correia** [comment]
Alright, thanks. I'll give that a try.

**Comment by buffaloDeveloper** [comment]
I've got a similar need to add connections to the docker image.  @ze-correia what did you end up doing?  Can you please share.
