### ISSUE TITLE
How to avoid Repeating Enviromental Variables?

### ISSUE THREAD

**Issue by athenawisdoms** [bitnami/bitnami-docker-airflow#44]
**Description**

Setting enviromental variables requires a lot of repetition. Is it possible to reduce the repetition which can be error-prone?

**Describe the results you received:**

To set an environmental variable like `AIRFLOW_LOAD_EXAMPLES=no` or `AIRFLOW_EXECUTOR=LocalExecutor`, it must be repeated 3 times in total: for `airflow-scheduler`, `airflow-worker` and `airflow`.

**Describe the results you expected:**

The environmental variable should only be required to set once, and be applied to all the relevant containers.

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:    
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 125.8GiB
 Name: foo-bar
 ID: HQ5V:XYG4:L75I:GV7J:7C76:24MU:A44Z:BTCN:F7RO:KOA4:2R2I:NNLJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using Docker for Linux on Ubuntu 20.04.

**Comment by ze-correia** [comment]
My suggestion is to use a `.env` file, as described [here](https://docs.docker.com/compose/compose-file/#env_file).

**Comment by juan131** [comment]
Hi @athenawisdoms 

I agree with @ze-correia, that can be a good alternative.

I know it's kind of repetitive to set the environment variable on every container that needs them, but there's very little we can do regarding this. Docker (and other container platforms) offer different alternatives to load the environment from a file/configmap, it's a matter to explore them and evaluate which one meet your needs.
