### ISSUE TITLE
How to add additional services to the containers

### ISSUE THREAD

**Issue by informatica92** [bitnami/bitnami-docker-airflow#49]
Hello all, 
I am trying to start an additional service on one of the container I have.
In particular I need to start the cloud sql proxy script file in order to connect to GCP cloud instances using a proxy.

First I added these lines into the Dockerfile:
```
COPY airflow-connection-credentials.json /etc/
RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /etc/cloud_sql_proxy && chmod +x /etc/cloud_sql_proxy
RUN mkdir /cloudsql; chmod 777 /cloudsql
```
Then I tryed different approaches to make it start on container startup:
 - I modified the run.sh adding the command I need but the container enters in boot loop in this case
 - I used update-rc.d and the LSB scripts but this approach needs run level to understand wich scripts have to be executed according to the run level (but containers don't have a runlevel associated)

Do you have other suggestions to start this script after the container creation?

**Comment by juan131** [comment]
Hi @informatica92 

Why do you want to run the proxy in the same container? This goes against the "one process, one container" principle that we should follow while designing cloud native applications.

Instead, I suggest using this proxy on a different container, and configure Airflow accordingly.

**Comment by informatica92** [comment]
Unfortunately, the cloud proxy needs to be on the same machine beause it creates a unix socket on a directory where all the connection with Cloud SQL are handled. 
Another solution I thought about is to mount the corresponding folder on the container but the service is executed on the host machine

**Comment by juan131** [comment]
Hi @informatica92 

> Unfortunately, the cloud proxy needs to be on the same machine because it creates a unix socket on a directory where all the connection with Cloud SQL are handled.

Are you running this container on K8s? Please note that you can use a sidecar container that guarantees you can share any directory between containers. They containers will also share the same network. More information in the link below:

- https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#how-pods-manage-multiple-containers

In case you're running the container on a different container platform (e.g. Docker Swarm or using Docker Compose) you can have replicate similar behaviours.

**Comment by informatica92** [comment]
I solved the issue with the solution I mentioned in the previous message (mounting an host directory into the worker container).
First of all I set up the script and the directory inside the host machine as indicated here: 
https://cloud.google.com/sql/docs/postgres/sql-proxy#unix_sockets

then, I added the following line for the worker service/container:
```
airflow-worker:
    ...
    volumes:
      - ...
      - /cloudsql:/cloudsql
```

On the host machine is also quite easy to set up the cloud sql script to start at boot time
