### ISSUE TITLE
can't install python package in container

### ISSUE THREAD

**Issue by LeonGraveland** [bitnami/bitnami-docker-airflow#5]
**Description**
I'm trying to install additional python packages, to use them in my scripts that the dags will activate. I'm looking for the best practice to do so, in this case I wan't to use the package azure-storage. Currently I bash into the container and try to install the package with pip3. 

Additional question, will i have to install this package in all the airflow containers? (Worker / Web / Scheduler)

**Steps to reproduce the issue:**

1. Bash into the container with docker exec -i -t [container ID] /bin/bash
2. use pip3 to install the package: pip3 install azure-storage

**Describe the results you received:**
```
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -I/opt/bitnami/python/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
```
I'm mostly interested in the best practice to install extra python packages using bitnami airflow images. 

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-1018-azure
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.766GiB
Name: gravelandairflow
ID: EHW7:T2I2:4EZU:NB2T:COGP:FY56:IFNN:43K3:FRBL:NGOH:CQUC:RZDW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

Running on a Linux VM on Azure

**Comment by rafariossaa** [comment]
Hi @LeonGraveland,
  Installing additional packages can be complicated depending on what the package needs. In your case, you need to install gcc, but it is very likely that you will need extra packages.
  What I would suggest is to add what is needed to the Dockerfile and then build your customized imaged, so you can reuse it, instead of accessing the container and doing it in the shell.

Best regards,
Rafael Rios Saavedra

**Comment by LeonGraveland** [comment]
Hi @rafariossaa ,
Thank you so much for your time to reply, really appreciate the effort!

I tried to rebuild the image by customizing the dockerfile in multiple ways, but unfortunately it didn't work out, I do not have experience adding python packages to a docker image. Any directions on how to add a python package to this images?

I also noticed the closed issue [https://github.com/bitnami/bitnami-docker-airflow/issues/1] where there is a request for the S3 hook. I'm trying to use the wasb_hook to communicate with azure blob storage, any change of having this hook added as wel to the bitnami images?

Kind regards,
Leon Graveland

**Comment by rafariossaa** [comment]
Hi @LeonGraveland,

This is what I tried:
- Clone this repository
- Go to bitnami-docker-airflow/1/debian-9
- Edit the Dockerfile and add this line under the other `RUN install_packages ...` line:
`RUN install_packages gcc  libstdc++-6-dev libssl-dev`
- Build the image: `docker build -t bitnami/airflow:1 .`
- Start the compose: `cd ../.. && docker-compose  up`
- Once started,  you should be able to enter in the airflow container a do `pip3 install azure_storage`.

Let me know if you have any problem.

Best regards,
Rafael Rios Saavedra

**Comment by LeonGraveland** [comment]
Hi @rafariossaa 
Thanks again for the effort and your response. I still have to test it, but it looks like a good solution. 

 However, would it be possible to add the `pip3 install azure_storage'` somewhere in the dockerfile? That way i can create my personal airflow images with all the dependencies I would love to have in all my projects. 

regards, Leon

**Comment by rafariossaa** [comment]
Hi @LeonGraveland ,
  In order to do that in the Dockerfile, you have to start the venv first.
  Try with this Dockerfile. It is the one you can find in the debian directory but I added the pip install line:
```

FROM bitnami/minideb-extras:stretch-r410
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    BITNAMI_PKG_EXTRA_DIRS="/opt/bitnami/airflow/dags" \
    HOME="/"

# Install required system packages and dependencies
RUN install_packages libbsd0 libbz2-1.0 libc6 libcomerr2 libedit2 libffi6 libgcc1 libgssapi-krb5-2 libicu57 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblzma5 libmariadbclient18 libncurses5 libnss-wrapper libreadline7 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtinfo5 libxml2 libxslt1.1 zlib1g
RUN bitnami-pkg install python-3.6.9-0 --checksum a3303f1de534403d1c1286b3f16a8052d48a06dbb7bf1cf004c7bd9db1b57873
RUN bitnami-pkg install postgresql-client-10.9.0-0 --checksum 1a1b4b3f6582abf88a6d109c0f55a65496f0a23b5fadc0b8642800d4d29179e0
RUN bitnami-pkg unpack airflow-1.10.3-2 --checksum 6fec23db262ae265ad3aa3d509d78091460257d45ac761b9db06d06180aeefd3

COPY rootfs /
ENV AIRFLOW_BASE_URL="" \
    AIRFLOW_DATABASE_HOST="postgresql" \
    AIRFLOW_DATABASE_NAME="bitnami_airflow" \
    AIRFLOW_DATABASE_PASSWORD="bitnami1" \
    AIRFLOW_DATABASE_PORT_NUMBER="5432" \
    AIRFLOW_DATABASE_USERNAME="bn_airflow" \
    AIRFLOW_DATABASE_USE_SSL="no" \
    AIRFLOW_EMAIL="user@example.com" \
    AIRFLOW_EXECUTOR="SequentialExecutor" \
    AIRFLOW_FERNET_KEY="" \
    AIRFLOW_FIRSTNAME="Firstname" \
    AIRFLOW_HOME="/opt/bitnami/airflow" \
    AIRFLOW_HOSTNAME_CALLABLE="" \
    AIRFLOW_LASTNAME="Lastname" \
    AIRFLOW_LOAD_EXAMPLES="yes" \
    AIRFLOW_PASSWORD="bitnami" \
    AIRFLOW_REDIS_USE_SSL="no" \
    AIRFLOW_USERNAME="user" \
    AIRFLOW_WEBSERVER_HOST="127.0.0.1" \
    AIRFLOW_WEBSERVER_PORT_NUMBER="8080" \
    BITNAMI_APP_NAME="airflow" \
    BITNAMI_IMAGE_VERSION="1.10.3-debian-9-r55" \
    LD_LIBRARY_PATH="/opt/bitnami/python/lib/:/opt/bitnami/airflow/venv/lib/python3.6/site-packages/numpy/.libs/:$LD_LIBRARY_PATH" \
    LD_PRELOAD="/usr/lib/libnss_wrapper.so" \
    LNAME="airflow" \
    NAMI_PREFIX="/.nami" \
    NSS_WRAPPER_GROUP="/opt/bitnami/airflow/nss_group" \
    NSS_WRAPPER_PASSWD="/opt/bitnami/airflow/nss_passwd" \
    PATH="/opt/bitnami/python/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/airflow/bin:/opt/bitnami/airflow/venv/bin:$PATH" \
    REDIS_HOST="redis" \
    REDIS_PASSWORD="" \
    REDIS_PORT_NUMBER="6379" \
    REDIS_USER=""

RUN . /opt/bitnami/airflow/venv/bin/activate && pip3 install azure_storage

EXPOSE 8080

USER 1001
ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "/run.sh" ]
```

Best regards

**Comment by LeonGraveland** [comment]
Dear @rafariossaa ,

I'm very grateful for your help! Will try this as soon as I got the time the coming days. 

Two additional questions: 
1. Should i adjust all the three airflow images (scheduler/worker/web) or just one of the three?
2. Is this package only available in that particular virtual environment within the container or is it 'widely available' in the entire container? Don't know if this question makes sense, but I'm curious whether I can import the package in my python code without any other actions.

Again, love your answers and solutions, really is helping me in my first steps in launching applications in containers. 

Best Regards,
Leon

**Comment by rafariossaa** [comment]
Hi @LeonGraveland,
  First of all, thanks for your kind words. 
  Regarding you questions:
  1) I am not a airflow expert, but I think you only need to add it to the worker container.
  2) As you can see in the dockerfile, it is installed in the virtual environment. If you python code is executed in the same virtual environment you should not have issues.

Best regards, 
Rafael Rios Saavedra
