### ISSUE TITLE
Does "Apache Airflow Container Image" includes all resources related to Apache Airflow?

### ISSUE THREAD

**Issue by veemvve** [bitnami/bitnami-docker-airflow#50]
Previously we were using "Apache Airflow Multi Tier" extension from Bitnami via Azure Marketplace which deploys all resources (Front-end, Scheduler, Worker, Database and Cache) related to Airflow using Azure VM. 

Recently we noticed that the above extension is no more available in Azure Marketplace and replaced with "Apache Airflow Container Image" which leverages Docker Container technologies. We deployed it using Azure Container Instance and noticed that not all resources related to Airflow exists. 

Is that expected - we have to deploy each resource separately using respective images like Postgresql, Redis etc?  
Or 
By default, this image provides all resources related to Airflow and somehow I'm missing it? If yes, please point me to any docs which helps to resolve the issue.

**Comment by juan131** [comment]
Hi @veemvve 

As you can see taking a look to this [Docker Compose](https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml), when working with containers we design them following a "micro-services" architecture. Therefore, there are different containers, each of them providing each of the components required for Apache Airflow. See:

- https://github.com/bitnami/bitnami-docker-airflow-scheduler
- https://github.com/bitnami/bitnami-docker-airflow-worker
- https://github.com/bitnami/bitnami-docker-redis
- https://github.com/bitnami/bitnami-docker-postgresql 

Regarding the "Apache Airflow Multi Tier" solution, it's still available. Please check the links below:

- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.airflow-multitier
- https://bitnami.com/stack/apache-airflow/multitier

**Comment by veemvve** [comment]
Thanks @juan131! Couple of follow-up questions, 

I'm trying to run [Docker Compose](https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml) in **Azure Subscription** but hitting a blocker. Tried with multiple options like Azure Cloud Shell, Docker Compose task in Azure Pipeline, 

**Error:**
Azure Cloud Shell: _docker-compose not found_ I installed docker compose using pip but still I'm getting the same error 
Azure pipeline Docker Compose task: 
_Creating network "network_name_default" with the default driver
HNS failed with error : The parameter is incorrect.
##[error]Creating network "msbizopsde-airflow_default" with the default driver
##[error]HNS failed with error : The parameter is incorrect._ 

Is there any other way to execute Docker Compose yaml file in Azure Subscription?

Also on the "Apache Airflow Multi Tier" extension, I'm not seeing it in Azure Marketplace as shown below,

![image](https://user-images.githubusercontent.com/44814792/87690395-42bffe80-c73e-11ea-9eca-95d387e77082.png)

Is there any other way to deploy this to Azure Subscription?

**Comment by juan131** [comment]
Hi @veemvve 

Yes, the solution was renamed very recently.

Regarding how to run the Docker Compose in Azure, I highly recommend you to ask the Azure support team about the alternatives you may have to do so:

- https://azure.microsoft.com/en-us/support/options/#overview
