### ISSUE TITLE
Docker Compose: Error - HNS failed with error : The parameter is incorrect

### ISSUE THREAD

**Issue by veemvve** [bitnami/bitnami-docker-airflow#51]
We are trying to execute this [docker-compose.yml](https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml) file in Azure Subscription and ended up with below error, 

[error]Creating network "airflow_default" with the default driver
[error]HNS failed with error : The parameter is incorrect.

We tried with multiple options like Azure CLI, Azure DevOps task (Docker Compose) but no luck. 

Also please note that we were able to execute this in our local environment and see all 5 Docker Containers. But unable to deploy new DAGS since I'm not sure how the mounting and file sharing works across all these resources. Do we have any document on it?

**Comment by marcosbc** [comment]
Hi @veemvve, that looks like an issue unrelated to the Bitnami Docker images. Searching for the error on Google, I saw this: https://stackoverflow.com/questions/45394360/hns-failed-with-error-the-parameter-is-incorrect Could you try the suggestion?

>Also please note that we were able to execute this in our local environment and see all 5 Docker Containers. But unable to deploy new DAGS since I'm not sure how the mounting and file sharing works across all these resources. Do we have any document on it?

To mount custom DAGs, just mount the directories/files to `/opt/bitnami/airflow/dags`. I.e. edit your `docker-compose.yml` file in the following way:

```diff
@@ -45,6 +45,7 @@
       - '8080:8080'
     volumes:
       - airflow_data:/bitnami
+      - ./dags:/opt/bitnami/airflow/dags
 volumes:
   airflow_scheduler_data:
     driver: local
```
