### ISSUE TITLE
AIRFLOW__XXX__XXX do not work as expected

### ISSUE THREAD

**Issue by claudexie** [bitnami/bitnami-docker-airflow#59]
```
root@airflow-webserver-5b4654f6d-swnt2:/# env | grep __
AIRFLOW__SMTP__SMTP_USER=claudexie
AIRFLOW__api__auth_backend=airflow.api.auth.backend.default
AIRFLOW__SMTP__SMTP_HOST=claudexie@tencent.com
root@airflow-webserver-5b4654f6d-swnt2:/# cat opt/bitnami/airflow/airflow.cfg | grep smtp
email_backend=airflow.utils.email.send_email_smtp
[smtp]
smtp_host=localhost
smtp_starttls=True
smtp_ssl=False
smtp_port=25
smtp_mail_from=airflow@example.com
root@airflow-webserver-5b4654f6d-swnt2:/# 

```

- Output of `docker-compose version` (if applicable): latest

**Comment by marcosbc** [comment]
@claudexie Could you share more information?

If you are referring to the SMTP credentials not being overridden by the envvar, that is expected as the environment variables are runtime overrides, meaning they will be taken in preference over the values in the config file.

**Comment by claudexie** [comment]
this issue somehow is gone！

**Comment by claudexie** [comment]
> @claudexie Could you share more information?
> 
> If you are referring to the SMTP credentials not being overridden by the envvar, that is expected as the environment variables are runtime overrides, meaning they will be taken in preference over the values in the config file.

i think it is because my container is started with somethings wrong

**Comment by claudexie** [comment]
> @claudexie Could you share more information?
> 
> If you are referring to the SMTP credentials not being overridden by the envvar, that is expected as the environment variables are runtime overrides, meaning they will be taken in preference over the values in the config file.

@marcosbc what kind of information  do you need？ thanks

**Comment by marcosbc** [comment]
@claudexie Exactly, the proper value is stored in the env. var which affects AirFlow at runtime.
