### ISSUE TITLE
Airflow LDAP authentication without TLS is broken. 'no' undefined

### ISSUE THREAD

**Issue by jpedrick** [bitnami/bitnami-docker-airflow#60]
**Description**
templates/web/deployment.yaml:
109:            - name: AIRFLOW_LDAP_USE_TLS
110:              value: {{ ternary "yes" "no" .Values.ldap.tls.enabled | quote }}

Should be "True", "False"
value: {{ ternary "True" "False" .Values.ldap.tls.enabled | quote }}

**Steps to reproduce the issue:**

1. Deploy airflow with ldap enabled
2. Fail due to 'yes', 'no' undefined in python.

**Describe the results you received:**
Airflow initialization fails

**Describe the results you expected:**
Airflow succeeds

**Comment by andresbono** [comment]
Thanks for raising this issue, @jpedrick. Would you like to open a PR addressing the change that you are proposing? Contributions are more than welcome!
