### ISSUE TITLE
Permissions Error when Mounting Host Directories

### ISSUE THREAD

**Issue by AlexDag** [bitnami/bitnami-docker-airflow#61]
**Description**
Making external mounting ( host directory) - shows the error of permissions

**Steps to reproduce the issue:**

1. [First Step]
edit original docker-compose.yml changing "volumes" as >
    volumes:
      - ./persist:/bitnami/postgresql
2. [Second Step]
save docker-compose.yml
run: sudo docker-compose up -d
3. [and so on...]

**Describe the results you received:**

docker logs 154e2f6c920b
postgresql 20:05:55.83 
postgresql 20:05:55.83 Welcome to the Bitnami postgresql container
postgresql 20:05:55.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 20:05:55.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 20:05:55.83 
postgresql 20:05:55.85 INFO  ==> ** Starting PostgreSQL setup **
postgresql 20:05:55.88 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 20:05:55.88 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql 20:05:55.89 INFO  ==> Loading custom pre-init scripts...
postgresql 20:05:55.90 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Permission for the folder "persist":
-rw-rw-r--. 1 airflow airflow  1626 Dec 11 17:05 docker-compose.yml
-rw-rw-r--. 1 airflow airflow   548 Dec 11 15:43 LICENSE
**drwxrwxr-x. 2 airflow airflow     6 Dec 11 17:04 persist**
-rw-rw-r--. 1 airflow airflow 20178 Dec 11 15:43 README.md
-rwxrwxr-x. 1 airflow airflow    26 Dec 11 15:57 start.sh
-rwxrwxr-x. 1 airflow airflow    25 Dec 11 16:14 stop.sh
**Version**

- Output of `docker version`:
```
Docker version 1.13.1, build 64e9980/1.13.1
```

- Output of `docker info`:
```
Containers: 22
 Running: 5
 Paused: 0
 Stopped: 17
Images: 43
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1160.2.1.el7.x86_64
Operating System: RHEL
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 31.26 GiB
Name: vsmart-apl01
ID: NAM4:SLB2:DDEF:25CD:QDXT:PVSK:V3EA:7VDJ:OWII:7NKY:SYUE:MCBS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: 
Https Proxy:
Registry: https://registry.access.redhat.com/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), registry.redhat.io (secure), docker.io (secure), docker.io (secure)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by AlexDag** [comment]
I've tried working on /tmp>
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - /tmp:/bitnami/postgresql

- there is the same error for the permissions.

**Comment by dani8art** [comment]
Hi @AlexDag,

Could you try the following?

```
$ mkdir -p /tmp/pg_volume
$ chow -R 1001:0  /tmp/pg_volume
```

```yaml
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - /tmp/pg_volume:/bitnami/postgresql
```

**Comment by AlexDag** [comment]
I've run docker with your instructions:
Here , it was created   /tmp/pg_volume
```
-rw-------. 1 1001 1001    80722 Dec  4 07:00 flink-jobgraph4403824833918224727.bin
-rw-------. 1 1001 1001   273078 Dec  4 08:00 flink-jobgraph6280736835554357293.bin
drwxr-xr-x. 2 1001 1001        6 Dec  4 08:06 hsperfdata_flink
srwx------. 1 root root        0 Dec  9 13:20 mysql.sock
drwxrwxr-x. 2 1001 1001        6 Dec 14 11:07 pg_volume
drwxr-xr-x. 2 root root        6 Dec 11 18:03 postgresql
```
I have running apache flink with user "1001"

The result of run the bitnami airflow :
[airflow@vsmart-apl01 bitnami-docker-airflow]$ do logs e0ac0b803533
```
postgresql 14:15:39.40 
postgresql 14:15:39.40 Welcome to the Bitnami postgresql container
postgresql 14:15:39.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 14:15:39.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 14:15:39.41 
postgresql 14:15:39.43 INFO  ==> ** Starting PostgreSQL setup **
postgresql 14:15:39.45 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 14:15:39.45 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql 14:15:39.46 INFO  ==> Loading custom pre-init scripts...
postgresql 14:15:39.47 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```
docker-compose.yml:
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - /tmp/pg_volume:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow

**Comment by dani8art** [comment]
I've tried twice but it is working fine for me

```
$ ls -la /tmp/pg_volume
total 20
drwxrwxr-x  3 1001 root  4096 Dec 15 12:15 .
drwxrwxrwt 20 root root 12288 Dec 15 12:17 ..
drwx------ 19 1001 root  4096 Dec 15 12:15 data
```

Are you mapping running your `.` directory? Could `apache flink` be blocking the read/write permission over this directory?

**Comment by AlexDag** [comment]
Could be "docker, docker-compose of the root count installation" - causes
these problems?
I use docker-compose by "sudo"

**Comment by AlexDag** [comment]
I put  the owner as "1001:1001" and the permission issues was out.
Another ERROR shows on:
```
2020-12-15 14:32:02.183 GMT [1] LOG:  pgaudit extension initialized
2020-12-15 14:32:02.185 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-12-15 14:32:02.186 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-12-15 14:32:02.193 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-12-15 14:32:02.220 GMT [89] LOG:  database system was shut down at 2020-12-14 21:21:57 GMT
2020-12-15 14:32:02.228 GMT [1] LOG:  database system is ready to accept connections
2020-12-15 14:32:16.023 GMT [96] LOG:  incomplete startup packet
2020-12-15 14:32:18.902 GMT [99] ERROR:  relation "log" does not exist at character 13
2020-12-15 14:32:18.902 GMT [99] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2020-12-15T14:32:18.889371+00:00'::timestamptz, NULL, NULL, 'cli_webserver', NULL, 'airflow', '{"host_name": "133b1329d72c", "full_command": "[''/opt/bitnami/airflow/venv/bin/airflow'', ''webserver'']"}') RETURNING log.id
2020-12-15 14:32:20.445 GMT [99] ERROR:  relation "dag" does not exist at character 547
2020-12-15 14:32:20.445 GMT [99] STATEMENT:  SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval 
	FROM dag 
	WHERE dag.is_active OR dag.is_paused
```

**Comment by dani8art** [comment]
Hi,

you will need to remove the rest of the volume so that you can start a fresh instance of airflow, could you try the following, please?

```
$ docker-compose down -v   <-- this will clean all volumes in this deployment
$ sudo rm -rf /tmp/pg_volume
$ mkdir -p /tmp/pg_volume
$ chown -R 1001:1001  /tmp/pg_volume
$ docker-compose up -d
```

**Comment by AlexDag** [comment]
ok,   after "$ docker-compose down -v"  : it run well  with persists on "custom host volume path".
One comment: I could not run it on /tmp/pg_volum as it is showing message>
`"ls: cannot open directory '/bitnami/postgresql/data': Permission denied"`
I created another host volume path,  /data/airflow,  and it is running well.
Thanks

**Comment by dani8art** [comment]
Great!! happy to hear that worked, Thanks so much for your feedback!
