### ISSUE TITLE
Apache Airflow: Issue with installing additional linux libraries and python packages post container creation thru bitnami helm charts

### ISSUE THREAD

**Issue by VORUSRIK000** [bitnami/bitnami-docker-airflow#62]
We have installed Apache Airflow on AKS using bitnami helm chart. App is running fine. For enabling Azure SQL connectivity from a DAG (say to execute some queries as part of DAG), we are trying to create a custom sql hook using pyodbc library. This library is not installed by default on Airflow containers using default image. When trying to install using pip3 install command, getting below errors related to missing gcc. 

**PYODBC ERROR**
_kubectl exec -c -- /opt/bitnami/airflow/venv/bin/pip3 install pyodbc
ERROR
Collecting pyodbc
Downloading pyodbc-4.0.30.tar.gz (266 kB)
Using legacy 'setup.py install' for pyodbc, since package 'wheel' is not installed.
Installing collected packages: pyodbc
Running setup.py install for pyodbc: started
Running setup.py install for pyodbc: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /opt/bitnami/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l5jtgxaj/pyodbc/setup.py'"'"'; file='"'"'/tmp/pip-install-l5jtgxaj/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-286fszn7/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/python/include/python3.6m/pyodbc
cwd: /tmp/pip-install-l5jtgxaj/pyodbc/
running install
running build
running build_ext
building 'pyodbc' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/bitnami/python/include/python3.6m -c src/buffer.cpp -o build/temp.linux-x86_64-3.6/src/buffer.o -Wno-write-strings
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1_

Installing gcc thru apt-get install is giving access error for root
**_Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?_**

Any pointers and direction on how we can get custom packages on installed bitnami images would help us.

**Comment by FraPazGal** [comment]
Hello @VORUSRIK000,

If you are using our helm chart, you can install additional python modules mounting the file `requirements.txt` file as explained in our [README](https://github.com/bitnami/charts/tree/master/bitnami/airflow#install-extra-python-packages). An example of the necessary configuration would be something similar to:

Conf.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-requirements
data:
  requirements.txt: |-
    pyodbc
```
Values.yaml:
```yaml
  worker:
    extraVolumes: |-
      - name: test-req
        configMap:
          name: test-requirements

    extraVolumeMounts: |-
      - name: test-req
        mountPath: /bitnami/python
```

A slightly more complex solution would be to customise our docker image to install the python module, though the first method is more flexible and should work for you just the same.

**Comment by VORUSRIK000** [comment]
I have tried the above suggestion, and still getting the same error. Since we have this on startup now, the worker container is going into CrashLoop and not starting. Core issue here is the linux image bitnami is using, which is missing essential "gcc" library that is required for pyodbc installation.
QUESTION: Alternate option specified is to tweak the image. Can this be used to install the missing "gcc" too? I am pretty novice in this area, so any pointers on how we can tweak the image and use it?
Below is error snapshot, which is happening on worker container startup, and is pretty much same as when we manually tried to install pyodbc.

[0m←[1mWelcome to the Bitnami airflow-worker container←[0m
Collecting pyodbc
  Downloading pyodbc-4.0.30.tar.gz (266 kB)
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py): started
  Building wheel for pyodbc (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/bitnami/airflow/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z6vlhhzb/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z6vlhhzb/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ai87z8xy
       cwd: /tmp/pip-install-z6vlhhzb/pyodbc/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/bitnami/airflow/venv/include -I/opt/bitnami/python/include/python3.6m -c src/buffer.cpp -o build/temp.linux-x86_64-3.6/src/buffer.o -Wno-write-strings
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
DEPRECATION: Could not build wheels for pyodbc which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pyodbc
    Running setup.py install for pyodbc: started
    Running setup.py install for pyodbc: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/bitnami/airflow/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z6vlhhzb/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z6vlhhzb/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n28w2i3b/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/airflow/venv/include/site/python3.6/pyodbc
         cwd: /tmp/pip-install-z6vlhhzb/pyodbc/
    Complete output (10 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/bitnami/airflow/venv/include -I/opt/bitnami/python/include/python3.6m -c src/buffer.cpp -o build/temp.linux-x86_64-3.6/src/buffer.o -Wno-write-strings
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1

**Comment by FraPazGal** [comment]
Oh, I misunderstood the issue. Yes the solution would be to install the necessary packages with `install_packages` and we need to run the container as `root`. This can indeed be done by customising our container and using the new image in the `docker-compose.yaml` file. There were a few packages needed for `pyodbc`, please give this `Dockerfile` a try and do not doubt to ask if there is anything you don't understand:

```Dockerfile
FROM docker.io/bitnami/airflow-worker:1-debian-10

USER root

RUN install_packages build-essential gcc unixodbc-dev
RUN /opt/bitnami/airflow/venv/bin/pip3 install pyodbc

USER 1001
```

**Comment by VORUSRIK000** [comment]
Thank you for the inputs. Considering we are using bitnami helm charts to enable this on AKS, and not the docker images directly, wonder how we can enable this thru the helm scripts. I tried looking at the configs/custom templates in helm github, but couldn't find a way to update the image details.
I actually tried installing gcc manually on the container, once it was created by helm. Was getting "/var/lib/apt/lists/partial" missing error. So assuming we cannot do the package installation post image creation.
Any pointers for this?

**Comment by FraPazGal** [comment]
Hi @VORUSRIK000,

If you are using our chart, you can replace the container image used in it using the image related parameters on `values.yaml`. You just need to push your custom image to your repository in any image registry and change the values of `xxxx.image.registry/repository/tag` to have the chart pull it:

```yaml
$ cat new_values.yaml

web:
  image:
    registry: docker.io
    repository: yourrepo/airflow
    tag: yourtag
```

Would that work for you?

**Comment by VORUSRIK000** [comment]
Apologize for not getting back earlier. We are able to get pyodbc installed using docker file. But along with the build libraries (gcc) and pyodbc package, we also had to install mssqlodb17 driver. Giving my docker below for ref. Thanks for the guidance. Will close this issue.

FROM docker.io/bitnami/airflow-scheduler:1-debian-10

USER root

RUN install_packages build-essential gcc unixodbc-dev
RUN /opt/bitnami/airflow/venv/bin/pip3 install pyodbc

ENV ACCEPT_EULA=Y
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        apt-transport-https \
        curl \
        gnupg \
 && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
 && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends --allow-unauthenticated msodbcsql17 mssql-tools \
 && apt-get -y clean

USER 1001

**Comment by danielcarvajal** [comment]
I had the same problem, but the workaround  does not work for me

**Comment by danielcarvajal** [comment]
I can not make Airflow connect to Azure SQL Database. The error messages is the following

ERROR - (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (bdpruebasserver.database.windows.net)\n')
Traceback (most recent call last):
  File "src/pymssql.pyx", line 636, in pymssql.connect
  File "src/_mssql.pyx", line 1964, in _mssql.connect
  File "src/_mssql.pyx", line 682, in _mssql.MSSQLConnection.__init__
  File "src/_mssql.pyx", line 1690, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (bdpruebasserver.database.windows.net)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/dag_tes_sql_to_df.py", line 60, in test_db
    conn= pymssql.connect(
  File "src/pymssql.pyx", line 642, in pymssql.connect
pymssql.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (bdpruebasserver.database.windows.net)\n')
[2021-03-30 23:41:46,306] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=Test_load_df_to_mssql_2, task_id=update_df_temp_1, execution_date=20210330T234109, start_date=20210330T234144, end_date=20210330T234146
[2021-03-30 23:41:49,202] {local_task_job.py:102} INFO - Task exited with return code 1

**Comment by VORUSRIK000** [comment]
Pymssql works with Azure SQL Database only through FreeTDS. You will have to install that in the image prior to using pymssql package.

But the better and recommended option to connect AzureSQL is to use pyodbc, and the referred thread has details on how to get that package in airflow image.

I think in airflow 2.x version, pyodbc is enabled through the providers. You can check that.
