### ISSUE TITLE
Python 3.7 or higher

### ISSUE THREAD

**Issue by tluzon-digibank** [bitnami/bitnami-docker-airflow#64]
Is there going to be an upgrade of Python for this image?

**Comment by carrodher** [comment]
Thanks for the suggestion, are you looking for a specific missing feature, extension, or functionality? We would like to understand if there is a reason behind the suggestion in order to prioritize the internal task if needed

**Comment by tluzon-digibank** [comment]
Well, our AI team here are developing and using libraries that require Python 3.7 or later and are blocked by the fact that this image runs Python 3.6.
Nevertheless, this Python version is becoming quite old.

Thank you very much for your time and effort.

**Comment by carrodher** [comment]
At this moment we are working on the release of the new major version (2.0), I just forwarded your suggestion to the team working on it. They will test a new python version with the new Airflow version, if everything works fine I can't see any cons on bumping the bundled python version to a more recent one.

**Comment by tluzon-digibank** [comment]
Airflow 2.0 is also something we look forward to, so that's great news.

Thank you for your time and effort.

**Comment by tom-vianai** [comment]
we have encountered several cases we had to use separate back ported versions of packages because 3.6 bundled in container can't run the 3.8 version our engineers are using in their notebooks.  Or had to modify code to be 3.6 compliant. 
 This introduces a risk for behavior differences or potential bugs.  I would very much support updating the images to 3.8 as soon as possible.

**Comment by carrodher** [comment]
I just added the on-hold label to prevent stale-bot to close the issue while we're working on it

**Comment by carrodher** [comment]
The latest image revision (`2.0.0-debian-10-r4`) contains python 3.8, see https://github.com/bitnami/bitnami-docker-airflow/commit/d11d2cf6e7525a1dafd57f1af4560d8e9d2ae1ee.

You can see the changes in the above image immutable tag (`-r4`) or any of the associated rolling tags that like `latest`, `2`, `2-debian-10`, `2.0.0`, etc)

```console
$ docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                    NAMES
a2bd4dfbe74c   bitnami/airflow:1-debian-10             "/app-entrypoint.sh …"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp   bitnami-docker-airflow_airflow_1
$ dcexec a2bd4dfbe74c
I have no name!@a2bd4dfbe74c:/$ python --version
Python 3.8.7
```

I am closing this issue, feel free to reopen it if something is not working as expected.

**Comment by tluzon-digibank** [comment]
Much appreciated!
