### ISSUE TITLE
I don't see my file in the Airflow user interface.

### ISSUE THREAD

**Issue by IngTecEduardo** [bitnami/bitnami-docker-airflow#7]
**Description**

I am putting into folder `/opt/bitnami/airflow/dags` my custom dags but user interface of Airflow doesn't show it when I refresh it.

**Steps to reproduce the issue:**

1. Run docker-compose.yml: I use this: [https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml](https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml) 
2. I put my custom dag in the bitnami volume `/var/lib/docker/volumes/airflow_airflow_data/_data`
3. Name my custom dag: _Adu_hello_world.py_ and it has the same permissions that examples.
4. My custom dag contains: 

```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.operators import MultiplyBy5Operator

def print_hello():
 return 'Hello Wolrd'

dag = DAG('Adu_hello_world', description='Hello world example', schedule_interval='0 12 * * *', start_date=datetime(2017, 3, 20), catchup=False)

dummy_operator = DummyOperator(task_id='dummy_task', retries = 3, dag=dag)

hello_operator = PythonOperator(task_id='hello_task', python_callable=print_hello, dag=dag)

multiplyby5_operator = MultiplyBy5Operator(my_operator_param='my_operator_param',
                                task_id='multiplyby5_task', dag=dag)

dummy_operator >> hello_operator

dummy_operator >> multiplyby5_operator
```

4. I move it to path `/opt/bitnami/airflow/dags` since console of the container `mv Adu_hello_world.py /opt/bitnami/airflow/dags/`

5. I refresh the Airflow user interface but it doesn't show anything. I have tested in Chrome and Firefox.

**Describe the results you received:**

I can't  start my custom dag, I don't see it in user interface.

**Describe the results you expected:**

See my custom dag in the user interface and so I can start it and put it to "on".

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens always.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:21:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89e8a
  Built:            Thu Jul 25 21:20:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-54-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.62GiB
 Name: erl
 ID: KV7I:LTRA:YSFP:3YOT:LHAM:SI6E:7RFA:4TEB:HQYL:CAVM:WRPL:GK3F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I have also tried adding a volume to path ` dags:/opt/bitnami/airflow/dags` in compose file and adding execution permissions obtaining the same result.

Thanks in advance.

**Comment by miguelaeh** [comment]
Hi @IngTecEduardo ,
Thank you very much for reporting. I can reproduce it. I am going to create an internal task to solve it. We will update this thread when we have the solution.
Thank you very much.

**Comment by tompizmor** [comment]
How much time have you waited for after mounting the DAG file? I have tested this in the past and it took a couple of minutes until I could see the DAG in the web interface.

**Comment by IngTecEduardo** [comment]
In my case, I think it is not due to the time. I have it running since yesterday and it is not shown in the user interface.

```
airflow@9799e4c85b6d:/opt/bitnami/airflow/dags$ ls -all
total 20
drwxrwxr-x 1       0 airflow 4096 Aug  4 09:06 .
drwxrwxr-x 1       0 airflow 4096 Aug  4 09:01 ..
-rwxrwxrwx 1 airflow airflow  807 Aug  4 09:03 Adu_hello_world.py
drwxr-xr-x 2 airflow airflow 4096 Aug  4 09:06 __pycache__
```

**Comment by miguelaeh** [comment]
I can confirm that it doesn't appear after 20 minutes.

**Comment by beltran-rubo** [comment]
Sorry for the delay @IngTecEduardo, the issue is the docker-compose.yaml does not include airflow-scheduler nor redis. Please use this one instead https://github.com/bitnami/bitnami-docker-airflow-scheduler/

We will work on adding the required components in the docker-compose.yml file in this repo

**Comment by beltran-rubo** [comment]
Please try again with the new docker-compose.yaml file that is published now in this repository, that should fix your issue: https://github.com/bitnami/bitnami-docker-airflow

Please reopen this issue if you find any problems.

**Comment by hleb-straltsou** [comment]
This issue is reproducible for me. I've tried steps described by @IngTecEduardo . Please help me.
