### ISSUE TITLE
OSError [Errno 5] Input/output error: '/opt/bitnami/airflow/logs/process_dag_v20/process_task_0/2021-02-28T19:59:25.616588+00:00'

### ISSUE THREAD

**Issue by aerasoft** [bitnami/bitnami-docker-airflow#70]
![Screen Shot 2021-02-28 at 8 11 55 PM](https://user-images.githubusercontent.com/24838294/109432060-5421f680-7a01-11eb-8e1b-3bcb64cd0b95.png)

Any help?

**Comment by Mauraza** [comment]
Hi @aerasoft,

when you get this error? could you add more information about this?
