### ISSUE TITLE
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful

### ISSUE THREAD

**Issue by arkachat** [bitnami/bitnami-docker-airflow#74]
postgre INFO  Found PostgreSQL server listening at airflow-postgresql:5432
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
postgre ERROR [canConnect] Connection with 'bn_airflow' user is unsuccessful
Error executing 'postInstallation': Cannot connect to PostgreSQL server:
psql: FATAL:  password authentication failed for user "bn_airflow"

helm install airflow ./ -n airflow -f values.yaml

[values.yml.txt](https://github.com/bitnami/bitnami-docker-airflow/files/6120747/values.yml.txt)

**Comment by arkachat** [comment]
This is a fresh install with no non-standard values

**Comment by juan131** [comment]
Hi @arkachat 

Did you previously install other chart releases using the same name in your cluster? It's likely that PostgreSQL is reusing previous PVCs and, therefore, the credentials don't match the data.

Take a look to the Troubleshooting guide below to obtain more information:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases

**Comment by arkachat** [comment]
Thanks for the Pointer @juan131 ,
I am wondering if there is a way to let the pvc for postgresql go automatically when airflow is deleted from helm.

**Comment by juan131** [comment]
I'm afraid there's not @arkachat 
I opened an issue at the Helm repo long time ago but it wasn't addressed yet. See https://github.com/helm/helm/issues/5156
