### ISSUE TITLE
Any chance to have java already installed on the docker image?

### ISSUE THREAD

**Issue by alebelucio** [bitnami/bitnami-docker-airflow#77]
Error missing JAVA_HOME

Try to run SparkSubmitOperator from apache-airflow-providers-apache-spark results in a missing JAVA_HOME error, but when try to find any java package, there is none already installed into the image.
Any chance to have it as standard, since a lot of other providers like JDBC use it also?

**Steps to reproduce the issue:**

1. Mount the /bitnami/python/requirements within the apache-airflow-providers-apache-spark in it.
2. Try to run any DAG that call an spark job

**Describe the results you received:**

[2021-03-17 22:23:34,764] {spark_submit.py:524} INFO - JAVA_HOME is not set

**Describe the results you expected:**
DAG spark job to run.

**Comment by javsalgar** [comment]
Hi,

Adding Java to the container would imply a substantial increase in its size, so in principle we don't have any plans to add it unless there's a clear demand of using Java Spark jobs from the community. I'd like to leave this thread open to see if more users have this need with the container. Right now, my advice would be to fork the Airflow container and add Java to it.

If you add this line to the Dockerfile, you will have Java 11 in the container

```
RUN wget -nc -P /tmp/bitnami/pkg/cache/ https://downloads.bitnami.com/files/stacksmith/java-11.0.10-0-linux-amd64-debian-10.tar.gz && \
    echo "68b909cfb5c98625e7d0db5c6eb82a34eca9b8940ada38b7eaa0c238bb510b57  /tmp/bitnami/pkg/cache/java-11.0.10-0-linux-amd64-debian-10.tar.gz" | sha256sum -c - && \
    tar -zxf /tmp/bitnami/pkg/cache/java-11.0.10-0-linux-amd64-debian-10.tar.gz -P --transform 's|^[^/]*/files|/opt/bitnami|' --wildcards '*/files' && \
    rm -rf /tmp/bitnami/pkg/cache/java-11.0.10-0-linux-amd64-debian-10.tar.gz
```

You should also set the JAVA_HOME env var.

```
ENV JAVA_HOME="/opt/bitnami/java"
```

**Comment by alebelucio** [comment]
Hi Javier,

Thank you for your quickly reply, in fact we use the helm bitnami airflow image and to workaround the JAVA_HOME missing issue I`d extracted the openjdk 8 to a pvc(persistent volume) mounted it as extra volume inside the container passing its path as a extraEnvVars. 
The openjdk 8 will increase 274 MB in image, openjdk 11 - 310MB it is some kind considerable but not as much if you consider the overall benefits.
I know that we can build our own image with it but every time bitnami upgrades I´ll have to reprocess the image, that´s why my the solution above appears to me more flexible.

Cheers.

**Comment by javsalgar** [comment]
Wow! That's impressive! Thanks for the input! Let's see what the community says on the matter
