### ISSUE TITLE
airflow 2.0.2 image unavailable 

### ISSUE THREAD

**Issue by ShawnMcGough** [bitnami/bitnami-docker-airflow#79]
**Description**

**airflow** 2.0.2 image is [not available](https://hub.docker.com/r/bitnami/airflow/tags?page=1&ordering=last_updated&name=2.0.2) from docker hub.
**airflow-worker** 2.0.2 is [available](https://hub.docker.com/r/bitnami/airflow-worker/tags?page=1&ordering=last_updated&name=2.0.2).
**airflow-scheduler** 2.0.2 is [available](https://hub.docker.com/r/bitnami/airflow-scheduler/tags?page=1&ordering=last_updated&name=2.0.2).

**Steps to reproduce the issue:**

1. check the links above, observe airflow 2.0.2 unavailable.

**Describe the results you expected:**

All three images (airflow, airflow-worker, airflow-scheduler) would be available in the same version (2.0.2).

Perhaps I'm just really early, but the README does include the 2.0.2 tag (which is a broken link at the moment):

![image](https://user-images.githubusercontent.com/64036/115588582-e70e3d00-a29c-11eb-9499-e35cb7fe2ece.png)

**Comment by Mauraza** [comment]
Hi @ShawnMcGough,

You are right, we are working on this version, I will update this thread when that version will be released. 

Thanks for reporting!

**Comment by izhangzhihao** [comment]
Same issue as https://github.com/bitnami/bitnami-docker-airflow-worker/issues/11

**Comment by carrodher** [comment]
Yes, is the same issue. In the above-mentioned issue, you can find a detailed explanation about why `bitnami/airflow:2.0.2` is not released at this moment.
About the mention in the README, it's a typo, this version is not available at this moment. We are working on fix the issues testing the Helm Chart

**Comment by izhangzhihao** [comment]
Now version 2.0.2 is available.

**Comment by Mauraza** [comment]
You are right @izhangzhihao, the 2.0.2 was released.

**Comment by ShawnMcGough** [comment]
Thanks! Closing issue.
