### ISSUE TITLE
ERROR Elasticbeanstalk Docker: false' is not a valid value for 'databaseUseSSL'. Allowed: yes, no

### ISSUE THREAD

**Issue by aerasoft** [bitnami/bitnami-docker-airflow#8]
```
  Docker container quit unexpectedly after launch: es and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-airflow/issues[0m
  [0m
  nami    INFO  Initializing airflow
  'false' is not a valid value for 'databaseUseSSL'. Allowed: yes, no. Check snapshot logs for details. (ElasticBeanstalk::ExternalInvocationError)
caused by: jq: error (at <stdin>:16): Cannot iterate over null (null)
  d301c86d66bb785ec084c05b9cedbebccdcaf262c6ac9f4caf9644816e85e741
  Docker container quit unexpectedly after launch: es and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-airflow/issues[0m
  [0m
  nami    INFO  Initializing airflow
  'false' is not a valid value for 'databaseUseSSL'. Allowed: yes, no. Check snapshot logs for details. (Executor::NonZeroExitStatus)
```

**Comment by rafariossaa** [comment]
Hi @aerasoft,
   Could you give me more context ? 
   As you can see [here](https://github.com/bitnami/bitnami-docker-airflow#user-content-use-an-existing-database) those parameters are not `true|false` but `yes|no`

**Comment by aerasoft** [comment]
I just deployed to Elasticbeanstalk docker using your image and set this AIRFLOW_DATABASE_USE_SSL to yes as Environment variable. 

For some reason this https://github.com/bitnami/bitnami-docker-airflow/blob/master/1/debian-9/rootfs/airflow-inputs.json#L6 is loading the global env databaseUseSSL as true. Can l edit this file to "yes"?

Also, l am getting this error below:
```
Docker container quit unexpectedly on Mon Aug  5 06:59:23 UTC 2019:
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/opt/bitnami/airflow/nss_passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file
```
https://github.com/bitnami/bitnami-docker-airflow/blob/master/1/debian-9/Dockerfile#L41-#L42

Because of the password error above: l couldn't log in with AIRFLOW_USERNAME and
AIRFLOW_PASSWORD l set as ENV variable. I had to use username: airflow and password: airflow before l was able to log in. 
![Screenshot 2019-08-05 at 7 16 42 AM](https://user-images.githubusercontent.com/24838294/62445927-01af2400-b751-11e9-8bcd-daae4bcb744f.png)

**Comment by aerasoft** [comment]
@rafariossaa Please any update?
