### ISSUE TITLE
Question: Where does Bitnami get its upstream package from?

### ISSUE THREAD

**Issue by msmerc** [bitnami/bitnami-docker-airflow#81]
I have a question - this image is basically pulling airflow via:

[RUN bitnami-pkg unpack airflow-2.0.1-1 --checksum 6f3f48e9b3717df7140abd7e007323682fd0a9c91c27ace5fbe0f38b6f2d2397](https://github.com/bitnami/bitnami-docker-airflow/blob/606f94f78377910bb8eaecd7de7cfeab0200c8d6/2/debian-10/Dockerfile#L18)

Looking at the `bitnami-pkg` script, this corresponds to a signed file from downloads.bitnami.com. Is it possible to see how this file is built?

Thanks!

**Comment by javsalgar** [comment]
Hi,

This file is a compiled tarball that our automated system builds. The process for creating that tarball is tracking and fetching the source code tarballs and applying the proper compilation recipe, which basically done by running the python compilation commands (setup.py and similar). Currently we don't have these recipes publicly available I'm afraid.

The tool we use for compiling is blacksmith: https://github.com/bitnami/blacksmith
