### ISSUE TITLE
How to turn off airflow login during first deployment

### ISSUE THREAD

**Issue by kangtao** [bitnami/bitnami-docker-airflow#83]
**Description**

Hi,

I was using debian-10 docker compose to deploy airflow and I realized that I could not bypass airflow login during the first deployment. What I have tried:

Ran docker-compose down -v and made sure there were no old containers. Added AIRFLOW__WEBSERVER__RBAC=False
and AIRFLOW__WEBSERVER__AUTHENTICATE=False as env variables and then ran  docker-compose up.  The airflow web container deployment failed and web was down.
Logs: 
airflow_1            | airflow 03:38:13.85 INFO  ==> Creating Airflow admin user
airflow_airflow_1 exited with code 1

Next, I tried docker-compose down -v again and did not add any additional env variables. The deployment went well and I can open airflow UI, which required login. Then I added  AIRFLOW__WEBSERVER__RBAC=False
and AIRFLOW__WEBSERVER__AUTHENTICATE=False, and ran  docker-compose up. The airflow web worked as well but with no login.

So I guess is that binami image must create a admin user at the first deployment? Is there a way to get rid of RBAC and auth completely using this image?

Thanks

**Comment by alemorcuq** [comment]
Yes, the container always creates an admin user at first deployment. See: https://github.com/bitnami/bitnami-docker-airflow/blob/ebef6c49b759a7224f8f36513fadf466bf42f01f/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L97

I'm not very familiar with Airflow itself. Can it be used without creating an admin user?
