### ISSUE TITLE
More configuration keys to enhance LDAP supports

### ISSUE THREAD

**Issue by echang0929** [bitnami/bitnami-docker-airflow#84]
**Description**

Can not support Microsoft AD setup of LDAP configurations: https://github.com/bitnami/charts/issues/6082

**Additional information you deem important (e.g. issue happens only occasionally):**

We need to add more configuration keys (https://flask-appbuilder.readthedocs.io/en/latest/config.html#configuration-keys) in the file:
https://github.com/bitnami/bitnami-docker-airflow/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh

1. Add more keys definition in the function https://github.com/bitnami/bitnami-docker-airflow/blob/bc4f982df8999eea2c1589c13743f7fffc72402c/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L233-L251
2. Update checking conditions to support more types of LDAP setups: https://github.com/bitnami/bitnami-docker-airflow/blob/bc4f982df8999eea2c1589c13743f7fffc72402c/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L39-L49

**Comment by miguelaeh** [comment]
Hi @echang0929 ,
Would you like to create a PR for this???

**Comment by echang0929** [comment]
@miguelaeh OK, let me try to create a PR today.

**Comment by miguelaeh** [comment]
Thank you very much 👏

**Comment by echang0929** [comment]
@miguelaeh I've updated two files in my own fork: 
* https://github.com/echang0929/bitnami-docker-airflow/blob/add-ldap-config-keys/2/debian-10/rootfs/opt/bitnami/scripts/airflow-env.sh
* https://github.com/echang0929/bitnami-docker-airflow/blob/add-ldap-config-keys/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh

As you see, I added all LDAP-related keys, mapped them to new environment variables, and updated some checking conditions of LDAP parameters. I only commented on old codes now. However, I have a question about two key parameters: 
* AIRFLOW_LDAP_URI
* AIRFLOW_LDAP_TLS_CA_CERTIFICATE

You see, I've replaced these two parameters with new ones which match mapping rules as other parameters: 
* AIRFLOW_LDAP_SERVER
* AIRFLOW_LDAP_TLS_CACERTFILE

And it has some impacts: 
1. Firstly, we need to update files README.md and docker-compose-ldap.yaml 
2. There are some inconsistencies between versions 1 and 2.
3. Needs to update other projects, e.g. Helm chart of Airflow

So, do you think I need to recover the old two parameters? 

Or another option: Could we add some more complicated codes to keep both old and new parameters? Is it valuable and acceptable?

**Comment by echang0929** [comment]
Test codes for checking LDAP parameters: 
```
#!/opt/local/bin/bash

aa="a"; bb="b"; cc="c";
# aa="a"; bb="b"; cc=;
# aa="a"; bb=; cc="c";
# aa="a"; bb=; cc=;
#
# aa=; bb="b"; cc="c";
# aa=; bb="b"; cc=;
# aa=; bb=; cc="c";
# aa=; bb=; cc=;

[[ -z "$aa" && -n "$bb" && -z "$cc" ]] \
    &&  echo "Missing cc"
[[ -z "$aa" && -z "$bb" && -n "$cc" ]] \
    &&  echo "Missing bb"
[[ -z "$aa" && -z "$bb" && -z "$cc" ]] \
    &&  echo "Need aa, or both bb and cc"
[[ -n "$aa" && (-n "$bb" || -n "$cc") ]] \
    &&  echo "Can not both aa and ??_*"
```

**Comment by miguelaeh** [comment]
Hi @echang0929 ,
thank you very much for the effort on this. 
About the parameters, we usually maintain both in order to have backwards compatibility. If the values they will contain have a similar format we use a kind of alias, like this on the Kafka container https://github.com/bitnami/bitnami-docker-kafka/blob/848024565b9b870454d3a5068edcd57f574a2c08/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L201

**Comment by echang0929** [comment]
Great suggestion, I'll learn and try to apply a similar method

**Comment by echang0929** [comment]
@miguelaeh I've updated two files in my fork: 
- https://github.com/echang0929/bitnami-docker-airflow/blob/add-ldap-config-keys/2/debian-10/rootfs/opt/bitnami/scripts/airflow-env.sh
- https://github.com/echang0929/bitnami-docker-airflow/blob/add-ldap-config-keys/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh

They include backwards compatibility. However, when I tried to test them using docker-compose I got a PostgreSQL connection issue. I do not think this issue is related to my changes, since I got the same issue when I use the original airflow image. (run docker-compose.yaml in the root path)
```airflow_1            | airflow 22:40:15.24 INFO  ==> Configuring Airflow webserver authentication
airflow_1            | airflow 22:40:15.25 INFO  ==> Enabling LDAP authentication
airflow_1            | airflow 22:40:15.30 INFO  ==> Configuring Airflow database
airflow_1            | airflow 22:40:15.31 INFO  ==> Configuring Celery Executor
airflow_1            | airflow 22:40:15.33 INFO  ==> Waiting for PostgreSQL to be available at postgresql:5432...
postgresql_1         | 2021-06-03 22:40:15.340 GMT [144] LOG:  incomplete startup packet
postgresql_1         | 2021-06-03 22:40:15.464 GMT [145] LOG:  incomplete startup packet
airflow-worker_1     | airflow-worker 22:40:15.46 INFO  ==> Persisting Airflow installation
airflow-worker_1     | airflow-worker 22:40:15.49 INFO  ==> Waiting for Airflow Webserser to be up
postgresql_1         | 2021-06-03 22:40:16.316 GMT [146] ERROR:  relation "connection" does not exist at character 55
postgresql_1         | 2021-06-03 22:40:16.316 GMT [146] STATEMENT:  SELECT connection.conn_id AS connection_conn_id
postgresql_1         | 	FROM connection GROUP BY connection.conn_id
postgresql_1         | 	HAVING count(*) > 1
postgresql_1         | 2021-06-03 22:40:16.340 GMT [146] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgresql_1         | 2021-06-03 22:40:16.340 GMT [146] STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted
postgresql_1         | 	FROM connection
postgresql_1         | 	WHERE connection.conn_type IS NULL
bitnami-docker-airflow_airflow_1 exited with code 1
```

So I think I need more time to figure out what is wrong with this issue. @miguelaeh, did you get this kind of issue before, any advice? Thanks.

**Comment by miguelaeh** [comment]
Could you check if you had a previous Postgresql volume that is being used? it can happen that the tables are not correct if you had persisted data from a previous version

**Comment by echang0929** [comment]
@miguelaeh I'm sure that I've pruned volumes, but I always got ERROR message in Postgresql container logs when I started airflow container (current bitnami version 2 on docker hub):
```
2021-06-05 23:36:35.506 GMT [150] LOG:  incomplete startup packet
2021-06-05 23:36:36.521 GMT [151] ERROR:  relation "connection" does not exist at character 55
2021-06-05 23:36:36.521 GMT [151] STATEMENT:  SELECT connection.conn_id AS connection_conn_id
	FROM connection GROUP BY connection.conn_id
	HAVING count(*) > 1
2021-06-05 23:36:36.545 GMT [151] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-06-05 23:36:36.545 GMT [151] STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted
	FROM connection
	WHERE connection.conn_type IS NULL
```

As I know, Airflow official docker-compose includes a db initialization step before running full airflow container. 
```
https://airflow.apache.org/docs/apache-airflow/2.0.2/start/docker.html
```

Do you think there is any gaps?

**Comment by echang0929** [comment]
Looks like Airflow official docker-compose has the similar ERROR:
```
2021-06-06 03:12:55.606 UTC [98] ERROR:  relation "log" does not exist at character 13
2021-06-06 03:12:55.606 UTC [98] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2021-06-06T03:12:55.595975+00:00'::timestamptz, NULL, NULL, 'cli_upgradedb', NULL, 'default', '{"host_name": "fdfb8688018d", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2021-06-06 03:12:55.802 UTC [98] ERROR:  relation "connection" does not exist at character 55
2021-06-06 03:12:55.802 UTC [98] STATEMENT:  SELECT connection.conn_id AS connection_conn_id
	FROM connection GROUP BY connection.conn_id
	HAVING count(*) > 1
2021-06-06 03:12:55.804 UTC [98] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-06-06 03:12:55.804 UTC [98] STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted
	FROM connection
	WHERE connection.conn_type IS NULL
```

Let me do more investigation and testings.

**Comment by miguelaeh** [comment]
I think you are using a docker-compose right? Could you share it so I can help with that?

**Comment by echang0929** [comment]
For Airflow official version: https://github.com/apache/airflow/blob/2.0.2/docs/apache-airflow/start/docker-compose.yaml, I followed the guide: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#initializing-environment
```
mkdir ./dags ./logs ./plugins
echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env

docker-compose up airflow-init
```
I've submitted an issue at Airflow repository: https://github.com/apache/airflow/issues/16332

For bitnami airflow docker, I followed:
```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-airflow/master/docker-compose.yml
$ docker-compose up
```
Even, following the command line step by step: https://github.com/bitnami/bitnami-docker-airflow#using-the-docker-command-line, I got the similar ERRORs. 

However, I suppose it is not a major error, esp for LDAP testing. I will test my codes soon.

**Comment by miguelaeh** [comment]
Hi @echang0929 ,
I am able to reproduce the issue. It seems that despite of that error in the postgresql log, Airflow seems to be working fine.
It could be an upstream issue, since it seems to happen in the upstream one too. Let's see what they answer to your issue.
Thank you very much for the work you did on this!
