### ISSUE TITLE
timeout reached before the port went into state "inuse"

### ISSUE THREAD

**Issue by cleveritcz** [bitnami/bitnami-docker-airflow#87]
Hello,
I am getting an unhealthy containers of airflow-scheduler and airflow-worker.

I got in UI this error:
`The scheduler does not appear to be running.

The DAGs list may not update, and new tasks will not be scheduled.` 

In bash I see:

> airflow-worker 18:20:34.66
> airflow-worker 18:20:34.66 Welcome to the Bitnami airflow-worker container
> airflow-worker 18:20:34.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
> airflow-worker 18:20:34.68 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues
> airflow-worker 18:20:34.68
> airflow-worker 18:20:34.69 INFO  ==> Enabling non-root system user with nss_wrapper
> airflow-worker 18:20:34.72 INFO  ==> ** Starting Airflow setup **
> airflow-worker 18:20:34.82 INFO  ==> No injected configuration file found. Creating default config file
> airflow-worker 18:20:34.83 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow version
> 2.1.0
> airflow-worker 18:20:36.01 INFO  ==> Configuring Airflow database
> airflow-worker 18:20:36.05 INFO  ==> Configuring Celery Executor
> airflow-worker 18:20:36.10 INFO  ==> Waiting for PostgreSQL to be available at postgresql:5432...
> airflow-worker 18:20:36.11 INFO  ==> Restoring persisted Airflow installation
> airflow-worker 18:20:36.16 INFO  ==> Waiting for Airflow Webserser to be up
> timeout reached before the port went into state "inuse"

> airflow-scheduler 18:20:34.53
> airflow-scheduler 18:20:34.53 Welcome to the Bitnami airflow-scheduler container
> airflow-scheduler 18:20:34.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-scheduler
> airflow-scheduler 18:20:34.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-scheduler/issues
> airflow-scheduler 18:20:34.55
> airflow-scheduler 18:20:34.56 INFO  ==> Enabling non-root system user with nss_wrapper
> airflow-scheduler 18:20:34.57 INFO  ==> ** Starting Airflow setup **
> airflow-scheduler 18:20:34.68 INFO  ==> No injected configuration file found. Creating default config file
> airflow-scheduler 18:20:34.69 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow version
> 2.1.0
> airflow-scheduler 18:20:35.96 INFO  ==> Configuring Airflow database
> airflow-scheduler 18:20:36.01 INFO  ==> Configuring Celery Executor
> airflow-scheduler 18:20:36.05 INFO  ==> Waiting for PostgreSQL to be available at postgresql:5432...
> airflow-scheduler 18:20:36.07 INFO  ==> Restoring persisted Airflow installation
> timeout reached before the port went into state "inuse"

I use this docker-compose:

> version: '2'
> services:
>   postgresql:
>     image: 'bitnami/postgresql:latest'
>     environment:
>       - POSTGRESQL_DATABASE=bitnami_airflow
>       - POSTGRESQL_USERNAME=bn_airflow
>       - POSTGRESQL_PASSWORD=bitnami1
>     volumes:
>       - /opt/airflow/postgres:/bitnami/postgresql
>     healthcheck:
>       test: ["CMD", "pg_isready", "-U", "bn_airflow"]
>       interval: 5s
>       retries: 5
>     restart: always
>   redis:
>     image: 'bitnami/redis:latest'
>     environment:
>       - ALLOW_EMPTY_PASSWORD=yes
>     volumes:
>       - /opt/airflow/redis:/bitnami
>     healthcheck:
>       test: ["CMD", "redis-cli", "ping"]
>       interval: 5s
>       timeout: 30s
>       retries: 50
>     restart: always
>   airflow-worker:
>     image: bitnami/airflow-worker:latest
>     environment:
>       - BITNAMI_DEBUG=true
>       - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
>       - AIRFLOW_EXECUTOR=CeleryExecutor
>       - AIRFLOW_DATABASE_NAME=bitnami_airflow
>       - AIRFLOW_DATABASE_USERNAME=bn_airflow
>       - AIRFLOW_DATABASE_PASSWORD=bitnami1
>       - AIRFLOW_LOAD_EXAMPLES=yes
>     healthcheck:
>       test:
>         - "CMD-SHELL"
>         - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
>       interval: 10s
>       timeout: 10s
>       retries: 5
>     volumes:
>       - /opt/airflow/worker:/bitnami
>     restart: always
>   airflow-scheduler:
>     image: bitnami/airflow-scheduler:latest
>     environment:
>       - BITNAMI_DEBUG=true
>       - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
>       - AIRFLOW_EXECUTOR=CeleryExecutor
>       - AIRFLOW_DATABASE_NAME=bitnami_airflow
>       - AIRFLOW_DATABASE_USERNAME=bn_airflow
>       - AIRFLOW_DATABASE_PASSWORD=bitnami1
>       - AIRFLOW_LOAD_EXAMPLES=no
>     healthcheck:
>       test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
>       interval: 10s
>       timeout: 10s
>       retries: 5
>     volumes:
>       - /opt/airflow/scheduler:/bitnami
>     restart: always
>   airflow:
>     image: bitnami/airflow:latest
>     environment:
>       - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
>       - AIRFLOW_EXECUTOR=CeleryExecutor
>       - AIRFLOW_DATABASE_NAME=bitnami_airflow
>       - AIRFLOW_DATABASE_USERNAME=bn_airflow
>       - AIRFLOW_DATABASE_PASSWORD=bitnami1
>       - AIRFLOW_PASSWORD=bitnami123
>       - AIRFLOW_USERNAME=user
>       - AIRFLOW_EMAIL=provoz@tipsport.cz
>     ports:
>       - '8080:8080'
>     volumes:
>       - /opt/airflow/persistence:/bitnami
>     depends_on:
>       redis:
>         condition: service_healthy
>       postgresql:
>         condition: service_healthy
>     restart: always

Could you help me?

**Comment by cleveritcz** [comment]
I resolve it.

**Comment by migruiz4** [comment]
Hi @cleveritcz,

I'm glad you were able to resolve the issue!

Usually, the error `timeout reached before the port went into state "inuse"` is caused by the scheduler or worker not being able to connect with the webserver.

For other users running into this same issue, did you solve the issue by adding `AIRFLOW_WEBSERVER_HOST` to your docker-compose?

**Comment by cleveritcz** [comment]
yes, exactly. It was missing.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing.
