### ISSUE TITLE
Adding Provider Package: apache-airflow-providers-microsoft-mssql

### ISSUE THREAD

**Issue by NiklasKnoll** [bitnami/bitnami-docker-airflow#89]
Hi, 
i tried adding the apache-airflow-providers-microsoft-mssql provider package using a requirements.txt. 

I added follwing packages in to the file:
`apache-airflow-providers-microsoft-azure`
`apache-airflow-providers-microsoft-mssql`

The startup succeeds and i am able to login. 
In the airflow providers list shown by using the command airflow providers list, the msswl provider is not shown.

If I want to create a new connection, the mssql connection type is not available to choose. 

I got all informations from the github readme https://github.com/bitnami/bitnami-docker-airflow/tree/606f94f78377910bb8eaecd7de7cfeab0200c8d6#installing-additional-python-modules

**Comment by rafariossaa** [comment]
Hi,
  Could you check if you have any errors in the logs ? Maybe there are some dependencies missing or something similar.

**Comment by NiklasKnoll** [comment]
I had a look... I do not see any missing dependencies. 
[
[logs.txt](https://github.com/bitnami/bitnami-docker-airflow/files/6622816/logs.txt)
](url)

**Comment by rafariossaa** [comment]
Did you saw any message in the log when listing the providers ?
I am not a airflow expert, I would suggest you to ask in airflow forums, maybe something more is needed to make it work.

**Comment by NiklasKnoll** [comment]
When I run the `airflow providers list` command the mssql provider package is not listed. 
As in the logs I provided the package gets installed successfully.

**Comment by rafariossaa** [comment]
Hi,
  In that case, I would recommend you to ask in airflow forums.

**Comment by NiklasKnoll** [comment]
The thing is that the installation of the package does only not work for your image. 
I did the same thing with the official apache images - it was working well.
We wanted to use the Azure Marketplace Images for our Customers, but they need more than the packages provided by the bitnami image used.

**Comment by alvneiayu** [comment]
hi @NiklasKnoll

I can not reproduce your issue, I created the requirements.txt (with both providers) like this:
```
$ cat requirements.txt 
apache-airflow-providers-microsoft-azure
apache-airflow-providers-microsoft-mssql
```
I mounted it using the docker-compose:
```
    volumes:
      - airflow_data:/bitnami
      - /home/bitnami/projects/temp/bitnami-docker-airflow/2/debian-10/requirements.txt:/bitnami/python/requirements.txt
```
after the Airflow initialization, I listed the providers:
```
I have no name!@b0b9d590ab9a:/$ airflow providers list | grep microsoft-mssql
apache-airflow-providers-microsoft-mssql  | Microsoft SQL Server (MSSQL) https://www.microsoft.com/en-us/sql-server/sql-server-downloads    | 1.1.0  
```
```
I have no name!@b0b9d590ab9a:/$ airflow providers list | grep microsoft-azure
apache-airflow-providers-microsoft-azure  | Microsoft Azure https://azure.microsoft.com/                                                    | 2.0.0  
```
Let me know if I can help you with something else.

Thanks a lot for your time.

Álvaro
