### ISSUE TITLE
How to install netbase: missing /etc/protocols 

### ISSUE THREAD

**Issue by aerasoft** [bitnami/bitnami-docker-airflow#9]
I followed this to install netbase as root inside docker and it didn't work https://stackoverflow.com/questions/40184788/protocol-not-found-socket-getprotobyname#answer-40185488

I need to install netbase because of this error l filed for Sentry https://github.com/getsentry/sentry-airflow/issues/9

**Comment by rafariossaa** [comment]
Hi @aerasoft,
   Could you give more detail of what you have tried, any errors that appeared, etc ?
