### ISSUE TITLE
install python package from git not working

### ISSUE THREAD

**Issue by knightoftheshadows** [bitnami/bitnami-docker-airflow#90]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

When I provide a git repository to be installed with pip in requirements.yaml it returns an error saying that git is not installed.

For example, in my requirements.yaml there is this line:

```
git+https://github.com/knightoftheshadows/downloader-cli.git#egg=downloader-cli
```

But after deploying, the pods keep crashing, and the logs include this:
```
Collecting downloader-cli
  Cloning https://github.com/knightoftheshadows/downloader-cli.git to /tmp/pip-install-ftoeot6r/downloader-cli_41ef80a74d554917a29d3431807709d1
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/knightoftheshadows/downloader-cli.git /tmp/pip-install-ftoeot6r/downloader-cli_41ef80a74d554917a29d3431807709d1
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Comment by alemorcuq** [comment]
From the error, it looks like `git` is not present in the image. You will need to extend the image to add `git` to your image.

However, I will discuss with the team the possibility to add `git` to the image by default as I think it's something useful.
