### ISSUE TITLE
How to change the local or default location of the log directory?

### ISSUE THREAD

**Issue by Vince2022** [bitnami/bitnami-docker-airflow#91]
**Description**

We are using Bitnami Airflow helm chart on our kubernetes cluster.  I am having trouble mounting a PVC, used for logging, to each of the web, scheduler and worker PODS. This PVC is also mounted in other REST endpoint PODS.  After changing the default BASE_LOG_FOLDER in Airflow, through ENV VARIABLE, I get permission denied messages in the Kubernetes logs for the scheduler when I try to run or trigger a DAG.  Airflow is still looking at the path "/opt/bitnami/airflow/logs" when it should be looking at "/logs", which is the mounted volume.  However, the "/logs" volume is not present in any of the PODS even though I added it through the Bitnami values file using:
1) scheduler.extraVolumes, scheduler.extraMountedVolumes
2) web.extraVolumes, web.extraMountedVolumes
3) worker.extraVolumes, worker.extraMountedVolumes
for example.

**Steps to reproduce the issue:**

1. Create a PVC volume with 777 permissions (for example: name: log-pvc)
2. Referencing the above PVC, create entries in the values.yaml to override the nil value for the following:
    a) scheduler.extraVolumes, scheduler.extraMountedVolumes
    b) web.extraVolumes, web.extraMountedVolumes
    c) worker.extraVolumes, worker.extraMountedVolumes

FOR EXAMPLE:
```
    worker:
        image:
            debug: true
        extraVolumes:
        - name: log-share
           persistedVolumeClaim:
               name: log-pvc
        extraVolumeMounts:
        - name: log-share
           mountPath: /logs
           readOnly: false
```

3. Set the environment variable to AIRFLOW__CORE__BASE_LOG_FOLDER = "/logs"
3. Install the bitnami helm chart for Apache Airflow 2.0.1
4. Log into the docker container running in the PODS to check for the existence of a logs folder at the root
5. Try to run or trigger a DAG
6. Check the logs of web, scheduler and worker components to see if permission denied errors are thrown

**Describe the results you received:**

Inside the logs for the docker container in the scheduler POD, we get "Permission Denied" could not find or write "/opt/bitnami/airflow/logs".  Furthermore, all the DAGS are stuck in the QUEUED state, because the tasks won't run.

**Describe the results you expected:**

I expected the DAGS to run, and all the logs should be written to the mounted volume using the following format:
{dag_id}/{task_id}/{execution_date}/{try_number}.log

**Additional information you deem important (e.g. issue happens only occasionally):**

We are on a PRIVATE Linux based Kubernetes cluster!

**Comment by migruiz4** [comment]
Hi @Vince2022,

I wasn't able to reproduce your issue using the following configuration for the scheduler, worker and web Airflow pods:
```yaml
  extraVolumes:
    - name: log-share
      persistentVolumeClaim:
        claimName: manual-claim
  extraVolumeMounts:
    - name: log-share
      mountPath: /logs
      readOnly: false
  extraEnvVars:
    - name: AIRFLOW__CORE__BASE_LOG_FOLDER
      value: /logs
```
 
I think your issue might be related to your Storage Class, and seems it is not only affecting the logs volume but also the Data volume.

Is it possible that you are using an NFS? This type of issue is frequently caused by how NFS handles permissions and ownership.

**Comment by Vince2022** [comment]
Hi @migruiz4,

We are using GPFS...
So far, I have been able to get the mounted volumes working in each of the component types: web, scheduler, worker.
However, the airflow scheduler still has an issue trying to write to the "mounted" log directory.
Bitnami seems to use a different format for writing log files then plain airflow.
The bitnami path format is: /opt/bitnami/airflow/logs/{component}/{date}/...
The {date} folder above is not accessible, perhaps because the owner/user is airflow.
All the other folders are owned by root

1) Does anyone know the proper way to set the local log path in Bitnami?
2) Does anyone know how to change to or make airflow use the root user?

Thanks!

**Comment by migruiz4** [comment]
Hi again @Vince2022,

Answering your questions:

> Does anyone know the proper way to set the local log path in Bitnami?

To change the local log path, you can add the environment variable to all of the Airflow pods using `extraEnvVars` as in my previously example
```
extraEnvVars:
  - name: AIRFLOW__CORE__BASE_LOG_FOLDER
    value: /logs
```
This will change airflow logging location to `/logs/{component}/{date}`.

----
> Does anyone know how to change to or make airflow use the root user?

Regarding the permissions issue, folders under `/opt/bitnami/airflow/logs/` are created and therefore owned by the Airflow user.

By default, the Bitnami Airflow container will run as a non-root user (1001).

If instead, you run the container as root using `containerSecurityContext.runAsUser=root`, the Airflow application will run as `$AIRFLOW_DAEMON_USER:$AIRFLOW_DAEMON_GROUP`, which defaults to `airflow:airflow`.

You could change the Airflow user and group too using extraEnvVars:
```
extraEnvVars:
  - name: AIRFLOW_DAEMON_USER
    value: root
  - name: AIRFLOW_DAEMON_GROUP
    value: root
```

But please keep in mind this could become a security flaw as vulnerabilities in Airflow could give attackers privileged access to your container.

If you want more information about non-root containers I'd recommend having a look at this link: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
