### ISSUE TITLE
need ability to put airflows flask process into debug logging mode

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow#95]
**Description**

I am trying to debug a connection issue between airflow and our LDAP server. Initial auth works fine (it doesnt complain about 
 bind credentials, giving bad admin creds will give an error) however no username and password combo will work at our login page. no errors or warnings appear in the container logs to state if ldap had an issue etc.
 
I started investigating more into this and reached the point i needed to put flask itself into debug mode so that the error logs from the auth plugin( loaded at the file /opt/bitnami/airflow/webserver_config.py which is generated on each docker container start) would output to the container logs.

AIRFLOW__LOGGING__LOGGING_LEVEL=debug is not enough as this is used AFTER the flask app starts but does not relate to the auth/ldap plugin loaded by flaskappbuilder.

I believe all that will be needed is `FLASK_ENV=development` to be allowed as an environment var but i may be wrong.

**Steps to reproduce the issue:**

1. set AIRFLOW__LOGGING__LOGING_LEVEL=debug
2. give incorrect details at login page

**Describe the results you received:**

no detailed errors about failed login will appear in container logs

**Describe the results you expected:**

ldap auth logs in debug mode

**Version**

- Output of `docker version`:

```
Docker version 20.10.7, build f0df350
```

- Output of `docker info`:

```
Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 5
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

hyperv vm

**Comment by Mauraza** [comment]
Hi @ITJamie,

Could you try adding the environment variable `BITNAMI_DEBUG=true`? 
I found this issue https://github.com/bitnami/charts/issues/6336 maybe it can help you

**Comment by ITJamie** [comment]
Ive tried that too since posting this. Still did not show the flask auth logs

**Comment by Mauraza** [comment]
Hi @ITJamie,

Did you add `AIRFLOW__LOGGING__FAB_LOGGING_LEVEL` https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#fab-logging-level?

**Comment by ITJamie** [comment]
Oooh. Thank you! Ill try this next.

**Comment by Mauraza** [comment]
Hi @ITJamie,

Did that variable help you?

**Comment by ITJamie** [comment]
That did work! Closing out
