### ISSUE TITLE
request: airflow.cfg - allow setting of secret_key with a variable

### ISSUE THREAD

**Issue by ITJamie** [bitnami/bitnami-docker-airflow#96]
**Description**

I need to be able to set secret_key in airflow.cfg. Its currently randomly generated when airflow.cfg file is first created

**Steps to reproduce the issue:**

1. start a new instance of bitnami-airflow docker container. view /opt/bitnami/airflow/airflow.cfg - secret_key variable is generated
2. remove existing volume. repeat step 1, there will be a different generated var

**Describe the results you received:**

as above the airflow.cfg is generated net-new on any volume clear of airflow. this causes secret_key to rotate. multiple machines can end up with different secret_keys.

**Describe the results you expected:**

currently no way to set this variable. its used by the webapp but also by airflow-workers for celery log access

**Additional information you deem important (e.g. issue happens only occasionally):**

This is important for users who are attempting to have HA airflow but do not have shared storage between hosts. because of this there are different keys across both hosts and can cause crsf errors. it also causes issues with remote airflow-workers as they also end up with different keys and have issues viewing logs from job runs.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1039-azure
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.791GiB
 Name: airflow
 ID: I37J:KB2J:ETIR:KZ7C:GCKS:MIUB:QGPH:R6KQ:QPIL:MULN:BTHI:VMVN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

ubuntu vms. using docker-compose and haproxy as a frontend / loadbalancer

**Comment by juan131** [comment]
Hi @ITJamie 

Did you try to set the `AIRFLOW_FERNET_KEY` env. variable as suggested in the Configuration section and examples?

- https://github.com/bitnami/bitnami-docker-airflow#airflow-configuration

AFAIK that's the key used to encrypt communications. You can find more information in the Airflow docs:

- https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html

**Comment by ITJamie** [comment]
That did infact work. It might be worth updating the docs a bit to mention the importance of this
